/* Mobile controls for governance, causal histories, catalog and training exports. */
(function(G){'use strict';const U=G.UI,W=G.WORLD,X=G.CIVIL,E=U.esc,A=U.A;
const dim=t=>'<div class="dim">'+t+'</div>',card=(t,h)=>'<section class="card"><h3>'+E(t)+'</h3>'+h+'</section>',row=h=>'<div class="item">'+h+'</div>',btn=(t,a,d={})=>'<button type="button" class="sm ap-action" data-a="'+a+'" '+Object.entries(d).map(([k,v])=>'data-'+k+'="'+E(v)+'"').join(' ')+'>'+E(t)+'</button>';
const kind=d=>X.actions[d.id]?'กิจกรรมตามเงื่อนไข':d.execution==='outcome'||d.handler==='event'||['SET_GOAL','COMPLETE_GOAL','FAIL_GOAL','ABANDON_GOAL','SECT_SHORTAGE','FIND_TREASURE','MOURN'].includes(d.id)?'เหตุการณ์หรือผลลัพธ์':'งานประจำหรือระบบเดิม';
U.M.civilCatalog=()=>card('กิจกรรมและเหตุการณ์ของโลก',dim('ทุกคำมีระบบรองรับ แต่ผู้กระทำต้องมีสิทธิ์ เป้าหมาย ผู้เกี่ยวข้อง และทรัพยากรครบก่อนลงมือ ผลเหตุการณ์ไม่ใช่ทางเลือกที่กดทำได้เอง')+Object.entries(G.N.actionCategories).map(([cat,name])=>'<details><summary>'+E(name)+' ('+Object.values(G.ACTIONS).filter(d=>d.category===cat).length+')</summary>'+Object.values(G.ACTIONS).filter(d=>d.category===cat).map(d=>row('<b>'+E(d.name)+'</b>'+dim(kind(d))+(W.state().debug?dim(E(d.id)):''))).join('')+'</details>').join(''));
U.M.civilGovernment=()=>{const g=X.group('player'),leader=X.leader('player'),people=X.members('player'),c=g.case,training=X.state().training;
 return card('อำนาจและความเป็นธรรม',dim('ความชอบธรรม '+G.f1(g.legitimacy)+' • ความตึงเครียด '+G.f1(g.unrest)+' • ความปลอดภัย '+G.f1(g.security))+dim('ความไม่พอใจสะสมเป็นข้อร้องเรียน กลุ่มสนับสนุน และการท้าทายได้ สมาชิกไม่ก่อกบฏโดยไม่มีเงื่อนไข')+btn('ทะเบียนกิจกรรมทั้งหมด','civil-catalog'))+
 card('ข้อร้องเรียนที่รอคำตอบ',people.filter(a=>X.life(a).petition?.status==='open').map(a=>row('<b>'+E(a.name)+'</b>'+dim('เรื่อง '+E(({medicine:'ขอยารักษา',allowance:'ขอเงินช่วยเหลือ',fairness:'ความเป็นธรรม'})[X.life(a).petition.type]||'การบริหาร')+' • ครบกำหนดวัน '+X.life(a).petition.due)+btn('ตรวจและชดเชย (ทุน 2)','civil-grievance',{id:a.id}))).join('')||dim('ยังไม่มีข้อร้องเรียนเปิดอยู่'))+
 card('การท้าทายอำนาจ',c?dim(E(W.person(c.challenger)?.name||'ผู้ท้าชิง')+' • ผู้สนับสนุนถ่วงน้ำหนัก '+G.f1(X.support('player',c.challenger))+' • '+E(({petition:'รอผู้นำตอบรับ',vote:'รอการลงมติ',conflict:'ความขัดแย้งรุนแรง'})[c.phase])+' • วันกำหนด '+c.due)+btn('ตรวจสอบและเจรจา (ทุน 10)','civil-case',{choice:'audit'})+btn('เปิดลงมติ','civil-case',{choice:'vote'})+btn('ปฏิเสธข้อเรียกร้อง','civil-case',{choice:'refuse'}):dim('ยังไม่มีผู้ยื่นท้าทาย'))+
 card('ฐานสนับสนุนและความต้องการ',people.map(a=>row('<b>'+E(a.name)+'</b>'+dim('พอใจ '+G.f1(X.sat(a))+' • ภักดี '+G.f1(X.loyalty(a))+' • คับข้องใจ '+G.f1(X.life(a).grievance)+' • อิทธิพล '+G.f1(X.life(a).influence))+dim('สนับสนุน '+E(W.person(a.b.cohort)?.name||'ยังไม่มีฝ่าย')+' • เสียงถ่วงน้ำหนักที่ได้รับ '+G.f1(X.support('player',a.id)))+btn('ดูชีวิตและผลกิจกรรม','world-person',{id:a.id}))).join(''))+
 card('ขบวนค้าและภารกิจ',X.state().caravans.filter(c=>c.from==='player'||c.to==='player').map(c=>row(E(X.groupName(c.from))+' → '+E(X.groupName(c.to))+dim(E(G.RES[c.key].n)+' '+G.f1(c.qty)+' • '+E(({moving:'กำลังขนส่ง',lost:'ถูกปล้นและคืนเงินผู้ซื้อ',delivered:'ส่งมอบแล้ว',cancelled:'ยกเลิกและคืนของกับเงินค้ำ'})[c.status])))).join('')||dim('ยังไม่มีขบวนสินค้า'))+
 card('เก็บผลเพื่อฝึกการตัดสินใจ',dim('สุ่มเก็บทุก 20 การตัดสินใจ พร้อมทางเลือกและผลหลัง 30 / 90 / 180 วัน ข้อมูลนี้เป็นผลจากการเล่น ยังไม่ได้ฝึกโมเดลหรือพิสูจน์ว่าทางเลือกที่ไม่ได้เลือกด้อยกว่า')+dim('รอติดตาม '+training.pending.length+' • ครบระยะ '+training.samples.length+' • ตัดรายการเกินเพดาน '+training.dropped)+btn(training.enabled?'หยุดเก็บข้อมูล':'เริ่มเก็บข้อมูล','civil-training')+btn('ส่งออกข้อมูลฝึก AI','civil-export'))+
 card('เหตุการณ์กิจการล่าสุด',X.state().history.filter(h=>h.group==='player').slice(0,20).map(h=>row('วัน '+h.day+' • '+E(h.text))).join('')||dim('ยังไม่มีประวัติกิจการใหม่'));
};
A['civil-open']=()=>U.open('civilGovernment');A['civil-catalog']=()=>U.open('civilCatalog');
A['civil-grievance']=d=>{const a=X.leader('player'),t=W.person(d.id),text=a&&t?X.execute(a,X.make(a,'RESOLVE_GRIEVANCE',{person:t.id})):null;G.save('auto');U.res({ok:!!text,msg:text||'ผู้ร้องหรือผู้นำไม่พร้อม เงินสำรองไม่พอ หรือข้อร้องเรียนถูกปิดแล้ว'});};
A['civil-case']=d=>{const ok=X.resolveCase('player',d.choice);G.save('auto');U.res({ok,msg:ok?'ดำเนินการตามคำตอบแล้ว':'ยังดำเนินการไม่สำเร็จ ตรวจเงินทุนและสถานะการท้าทาย'});};
A['civil-training']=()=>{const t=X.state().training;t.enabled=!t.enabled;G.save('auto');U.open('civilGovernment');};
A['civil-export']=()=>{const text=X.exportTraining(),b=new Blob([text],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download='MeKha-ข้อมูลฝึก-วัน'+G.S.day+'.json';document.body.appendChild(a);a.click();setTimeout(()=>{URL.revokeObjectURL(a.href);a.remove()},1000);U.toast('ส่งออกข้อมูลฝึกแล้ว ดูในโฟลเดอร์ดาวน์โหลด');};
const home=U.V.home;U.V.home=()=>home()+card('สภาสำนักและชีวิตโลก',btn('ข้อร้องเรียน / อำนาจ / การค้า / ข้อมูลฝึก','civil-open'));
const simulation=U.M.worldSimulation;U.M.worldSimulation=()=>simulation()+card('กิจการโลก 2.1',btn('สภาสำนักและผลกิจกรรม','civil-open')+btn('กิจกรรมและเหตุการณ์ทั้งหมด','civil-catalog'));
const person=W.personSheet;W.personSheet=id=>{const a=W.person(id);if(!a)return person(id);const l=X.life(a),g=X.group(a.group);
return person(id)+card('ชีวิตและฐานอำนาจ',dim('ความพอใจ '+G.f1(X.sat(a))+' • ภักดี '+G.f1(X.loyalty(a))+' • คับข้องใจ '+G.f1(l.grievance))+dim('ความชอบธรรมสำนัก '+G.f1(g.legitimacy)+' • ความตึงเครียด '+G.f1(g.unrest)+' • อิทธิพล '+G.f1(l.influence))+dim('คู่ครอง '+E(W.person(l.partner)?.name||'ยังไม่มี')+' • อาจารย์ '+E(W.person(a.f?l.master:a.c.master)?.name||'ยังไม่มี'))+dim('สถานะ '+E(l.captive?'ถูกคุมขัง':l.travel?'เดินทางไป '+(G.LOCS[l.travel.location]?.n||X.groupName(l.travel.location)):l.study?'เรียน '+G.PATCH.arts[l.study.art].name:'อยู่ในสำนัก')))+card('สิ่งของ วิชา และหนี้',dim('วิชาที่เรียน '+X.arts(a).length+' • อุปกรณ์ '+X.gear(a).length+' • หนี้เปิด '+l.debts.filter(d=>['open','overdue'].includes(d.status)&&d.borrower===a.id).length)+X.gear(a).slice(0,8).map(i=>dim(E(G.PATCH.items[i.def].name))).join(''))+card('กิจกรรมที่เปลี่ยนชีวิต',l.records.map(r=>row('วัน '+r.day+' • '+E(r.text))).join('')||dim('ยังไม่มีบันทึกใหม่'));};
U.M.worldPerson=id=>W.personSheet(id);
})(window.G);
