/* Organizational work, access-controlled techniques, recruitment and migration between sects. */
(function(G){'use strict';const X=G.CIVIL,W=G.WORLD,N=G.N,P=G.PATCH,C=G.clamp;
X.define('MANAGE_RESOURCES','ตรวจคลังและกำหนดความจำเป็น','sect',{actors:['elder'],cooldown:7,check:a=>X.balance(a.group,'food')<X.members(a.group).length*20||X.group(a.group).unrest>15,run:a=>{X.group(a.group).reports.unshift({day:G.S.day,actor:a.id,type:'stock',petition:null});X.group(a.group).reports=X.group(a.group).reports.slice(0,24);X.life(a).influence=C(X.life(a).influence+.3,0,100);X.group(a.group).security=C(X.group(a.group).security+.1,0,100);return 'ตรวจคลังเสบียง '+G.f1(X.balance(a.group,'food'))+' และเงิน '+G.f1(X.balance(a.group,'silver'))+' ส่งรายงานให้สภา';},priority:()=>34});
X.define('BUY_RESOURCES','ซื้อวัตถุดิบจากตลาดจำกัด','economy',{actors:['sect'],costs:{silver:'market_price'},cooldown:7,choose:a=>{const key=['herb','ore','stone','wood'].find(k=>X.balance(a.group,k)<2);return key?{resource:key}:null;},check:(a,p)=>{const key=p.data.resource,e=W.state().economy;return ['herb','ore','stone','wood'].includes(key)&&e[key+'Supply']>=1&&X.canPay(a.group,{silver:G.RES[key].p*(key==='herb'?e.medicinePrice:1)});},run:(a,p)=>{const key=p.data.resource,e=W.state().economy,cost=G.RES[key].p*(key==='herb'?e.medicinePrice:1);if(e[key+'Supply']<1||!X.pay(a.group,{silver:cost},'ซื้อวัตถุดิบ'))return null;e[key+'Supply']--;X.add(a.group,key,1,'รับของจากตลาด');return 'ซื้อ '+G.RES[key].n+' 1 ราคา '+G.f1(cost)+' ลดสินค้าตลาดจริง';},priority:a=>a.f?50:0});
for(const [id,name]of [['BUILD_FACILITY','ก่อสร้างสถานที่'],['EXPAND_SECT','ขยายความจุสำนัก']])X.define(id,name,'sect',{actors:['sect'],cooldown:30,costs:{silver:50,wood:5,ore:2},choose:a=>{const g=X.group(a.group),facility=id==='EXPAND_SECT'?'dorm':!g.facilities.clinic&&X.members(a.group).some(t=>W.health(t)<70)?'clinic':!g.facilities.forge?'forge':!g.facilities.alchemy?'alchemy':null;return facility?{facility}:null;},check:(a,p)=>a.f&&Object.hasOwn(X.group(a.group).facilities,p.data.facility)&&X.group(a.group).facilities[p.data.facility]<4&&X.canPay(a.group,{silver:50,wood:5,ore:2}),run:(a,p)=>{if(!X.pay(a.group,{silver:50,wood:5,ore:2},name))return null;X.group(a.group).facilities[p.data.facility]++;return 'ใช้ทุนและวัสดุเพิ่ม '+({forge:'โรงตีอาวุธ',alchemy:'โรงโอสถ',clinic:'เรือนรักษา',dorm:'ที่พัก'}[p.data.facility])+' หนึ่งระดับ เปิดความสามารถจริง';},priority:a=>a.f?37:0});
X.define('REPAIR_FACILITY','ซ่อมสิ่งก่อสร้างเสียหาย','sect',{actors:['sect'],cooldown:7,costs:{silver:5,wood:1},check:a=>X.group(a.group).damage>0&&X.canPay(a.group,{silver:5,wood:1}),run:a=>{if(!X.pay(a.group,{silver:5,wood:1},'ซ่อมสิ่งก่อสร้าง'))return null;X.group(a.group).damage=Math.max(0,X.group(a.group).damage-5);return 'ซ่อมความเสียหายลง 5 ฟื้นความสามารถผลิตและป้องกัน';},priority:()=>70});
X.define('DISTRIBUTE_EQUIPMENT','จัดอุปกรณ์จากคลังให้สมาชิก','sect',{actors:['sect'],target:'near_person',choose:(a,c)=>X.toTarget(c.peers.find(t=>t.f&&X.chooseItem(t))),cooldown:7,check:(a,p,t)=>!!t.f&&!!X.chooseItem(t),run:(a,p,t)=>{const id=X.chooseItem(t);if(!X.giveItem(t,id))return null;W.relate(t,a.id,{gratitude:2,loyalty:1,debt:.2});X.loyalty(t,.5);for(const other of X.members(a.group).filter(o=>o.id!==t.id&&X.rank(o)===X.rank(t)&&W.attr(o,'amb')>75)){W.relate(other,t.id,{jealousy:1});}return 'จัด '+P.items[id].name+' จากคลังให้ '+t.name+' มีผลต่อกำลังและความสัมพันธ์';},priority:()=>48});
X.define('DISTRIBUTE_MEDICINE','จัดยารักษาตามอาการ','sect',{actors:['sect'],target:'near_person',choose:(a,c)=>X.toTarget(c.injured),costs:{herb:1},check:(a,p,t)=>W.health(t)<80&&X.canPay(a.group,{herb:1}),run:(a,p,t)=>{if(!X.pay(a.group,{herb:1},'รักษาสมาชิก'))return null;X.health(t,8);X.life(t).wounds=Math.max(0,X.life(t).wounds-1);W.relate(t,a.id,{gratitude:2,loyalty:1});return 'ใช้สมุนไพร 1 รักษา '+t.name+' สุขภาพเพิ่ม 8';},priority:()=>75});
X.define('SECT_TRAINING','จัดการฝึกหมู่ของสำนัก','sect',{actors:['elder'],cooldown:7,costs:{food:1,stone:.5},check:a=>X.canPay(a.group,{food:1,stone:.5})&&X.members(a.group).filter(t=>W.available(t)).length>=3,run:a=>{if(!X.pay(a.group,{food:1,stone:.5},'ฝึกหมู่'))return null;const people=X.members(a.group).filter(t=>W.available(t)).slice(0,6);for(const t of people){X.foundation(t,.1);X.fatigue(t,.5);W.relate(t,a.id,{respect:.3});}return 'ฝึกหมู่ '+people.length+' คน จ่ายเสบียงและหินปราณจริง';},priority:()=>40});
for(const [id,name]of [['ASSIGN_MISSION','มอบหมายภารกิจ'],['SECT_MISSION','รับภารกิจสำนัก']])X.define(id,name,'sect',{actors:id==='ASSIGN_MISSION'?['elder']:['character'],cooldown:14,choose:(a,c)=>{const person=id==='ASSIGN_MISSION'?c.peers.find(t=>W.available(t)&&!X.isLeader(t)):a;const site=c.sites.find(id=>G.LOCS[id].danger<=Math.max(1,W.realm(person||a))&&G.LOCS[id].k!=='trade');return person&&site?{person:person.id,site}:null;},check:(a,p)=>{const person=W.person(p.data.person);return !!person&&W.available(person)&&W.health(person)>80&&(person.f||G.S.patch.management.autoMissions&&!person.c.jobFix&&!person.c.mx.managementLock)&&X.canPay(a.group,{food:G.LOCS[p.data.site].dist*.3+1,silver:1});},run:(a,p)=>{const person=W.person(p.data.person),text=X.startTravel(person,p.data.site,'SECT_MISSION');if(!text)return null;X.group(a.group).missions.push({id:'mission'+X.state().next++,actor:person.id,site:p.data.site,started:G.S.day,status:'active'});X.group(a.group).missions=X.group(a.group).missions.slice(-16);return 'มอบหมาย '+person.name+' ไป '+G.LOCS[p.data.site].n+' ต้องนำผลงานจริงกลับมา';},priority:a=>a.f?36:8});
for(const [id,name]of [['RESEARCH_TECHNIQUE','ค้นคว้าตำรับวิชาสำนัก'],['CREATE_TECHNIQUE','สร้างแขนงวิชาส่วนตัว']])X.define(id,name,'martial',{cooldown:90,costs:{silver:20,stone:2},choose:a=>{const base=X.arts(a).find(id=>X.mastery(a,id)>=85);if(id==='CREATE_TECHNIQUE')return base?{art:base}:null;const art=Object.values(P.arts).find(d=>d.source==='scroll'&&d.tier<=2&&d.paths.includes(X.path(a))&&!(a.f?X.group(a.group).library:G.S.patch.knownArts).includes(d.id));return art?{art:art.id}:null;},check:(a,p)=>W.attr(a,'int')>65&&X.canPay(a.group,{silver:20,stone:2})&&(id==='CREATE_TECHNIQUE'?X.arts(a).includes(p.data.art)&&X.mastery(a,p.data.art)>=85&&X.life(a).variants.length<3:!!P.arts[p.data.art]&&P.arts[p.data.art].source==='scroll'&&P.arts[p.data.art].tier<=2&&(a.f?X.group(a.group).facilities.forge>=1:G.S.fac.library>=Math.max(1,P.arts[p.data.art].tier))),run:(a,p)=>{if(!X.pay(a.group,{silver:20,stone:2},name))return null;if(id==='CREATE_TECHNIQUE'){X.life(a).variants.push({base:p.data.art,name:P.arts[p.data.art].name+' · แขนงของ '+a.name,work:60,bonus:0});return 'เริ่มพัฒนาแขนงของ '+P.arts[p.data.art].name+' ต้องฝึกและทดลองอีก 60 ช่วงก่อนเกิดผล';}if(a.f){if(!X.group(a.group).library.includes(p.data.art))X.group(a.group).library.push(p.data.art);}else N.unlockArt(p.data.art,'ค้นคว้าสำนัก');return 'จ่ายทุนค้นตำรับ '+P.arts[p.data.art].name+' ผู้เรียนยังต้องผ่านสิทธิ์และใช้เวลา';},priority:a=>a.f?22:12});
X.define('RECRUIT_DISCIPLE','รับบุคคลจากประชากรเข้าสำนัก','sect',{actors:['sect'],cooldown:30,costs:{silver:28},check:a=>a.f&&a.f.roster.length<40&&a.f.pop>a.f.roster.length+5&&X.canPay(a.group,{silver:28,food:5}),run:a=>{if(!X.pay(a.group,{silver:28,food:5},'รับสมาชิกใหม่'))return null;const r={n:G.genName(G.ch(.4)),r:0};a.f.roster.push(r);if(a.f.troops>0)a.f.troops--;N.foreignInit(G.S,a.f);X.life(W.person(r.mx.id)).loyalty=60;return 'รับ '+r.n+' จากประชากรเดิม จ่ายทุนและเสบียง ไม่เพิ่มประชากรโลก';},priority:a=>a.f&&a.f.roster.length<Math.min(18,a.f.pop*.15)?35:0});
for(const [id,name]of [['PROMOTE_MEMBER','เลื่อนตำแหน่งสมาชิก'],['DEMOTE_MEMBER','ลดตำแหน่งสมาชิก'],['REWARD_MEMBER','ให้รางวัลสมาชิก'],['PUNISH_MEMBER','ลงโทษตามหลักฐาน']])X.define(id,name,'sect',{actors:['sect'],target:'near_person',choose:(a,c)=>X.toTarget(id==='PUNISH_MEMBER'||id==='DEMOTE_MEMBER'?c.peers.find(t=>X.life(t).evidence.some(e=>e.confidence>=.9)):c.peers.find(t=>X.life(t).influence>5||X.sat(t)<50)),cooldown:30,check:(a,p,t)=>id==='REWARD_MEMBER'?X.canPay(a.group,{silver:2}):id==='PUNISH_MEMBER'||id==='DEMOTE_MEMBER'?X.life(t).evidence.some(e=>e.confidence>=.9)&&X.rank(t)>0:!t.f?G.S.patch.management.autoPromote&&!t.c.mx.managementLock&&t.c.rank<3&&t.c.realm>=t.c.rank+1:X.life(t).influence>5&&t.c.mx.role!=='ผู้อาวุโส',run:(a,p,t)=>{if(id==='REWARD_MEMBER'){if(!X.canPay(a.group,{silver:2}))return null;X.add(a.group,'silver',-2,'รางวัล');t.b.wallet+=2;X.sat(t,2);X.loyalty(t,.5);W.relate(t,a.id,{gratitude:2});}
 else if(!t.f){const r=id==='PUNISH_MEMBER'?G.punish(t.c):G.promote(t.c,id==='DEMOTE_MEMBER'?-1:1);if(!r?.ok)return null;}
 else if(id==='PROMOTE_MEMBER'){t.c.mx.role='ผู้อาวุโส';X.sat(t,4);X.loyalty(t,1);}
 else{t.c.mx.role='ศิษย์';X.sat(t,-3);X.life(t).influence=Math.max(0,X.life(t).influence-3);if(id==='PUNISH_MEMBER'){X.life(t).evidence=X.life(t).evidence.filter(e=>e.confidence<.9);X.group(a.group).security=C(X.group(a.group).security+1,0,100);}}
 return name+' '+t.name+' ตามผลงานหรือหลักฐานจริง';},priority:()=>38});
X.moveForeign=(a,to)=>{const f=G.S.factions.find(f=>f.id===to&&!f.dead);if(!a.f||!f||f===a.f||f.roster.length>=40||X.war(a.group,to)||X.path(a)!==f.path)return false;const old=a.f;old.roster=old.roster.filter(r=>r!==a.c);old.pop=Math.max(0,old.pop-1);f.roster.push(a.c);f.pop++;a.c.mx.role='ศิษย์';a.b.cohort=null;X.life(a).master=null;X.life(a).disciples=[];X.life(a).loyalty=50;X.life(a).petition=null;if(old.mx.leader===a.id)old.mx.leader=old.roster[0]?.mx.id||null;N.foreignInit(G.S,old);N.foreignInit(G.S,f);return true;};
for(const [id,name]of [['LEAVE_SECT','ลาออกไปหาสำนักที่เหมาะสม'],['JOIN_SECT','ขอเข้าร่วมสำนักอื่น']])X.define(id,name,'sect',{target:'group',cooldown:180,choose:(a,c)=>{const group=c.groups.find(id=>{const f=G.S.factions.find(f=>f.id===id&&!f.dead);return f&&f.path===X.path(a)&&!X.war(a.group,id)&&f.roster.length<40&&X.balance(id,'food')>10;});return group?{group}:null;},check:(a,p)=>a.f&&!X.isLeader(a)&&X.loyalty(a)<25&&X.life(a).grievance>40&&!X.war(a.group,p.data.group)&&G.S.factions.some(f=>f.id===p.data.group&&!f.dead&&f.path===X.path(a)&&f.roster.length<40),run:(a,p)=>X.moveForeign(a,p.data.group)?name+' '+X.groupName(p.data.group)+' รักษาตัวตน เงิน วิชา และประวัติเดิม':null,priority:a=>X.loyalty(a)<20?75:0});
})(window.G);
