/* 2.1: shared actor/organization adapters. Currency and stock always have an owner. */
(function(G){'use strict';
const W=G.WORLD,N=G.N,P=G.PATCH,C=G.clamp,X=G.CIVIL={};
G.VERSION='2.1.0';G.SCHEMA=8;
X.state=()=>G.S.patch.civil;
X.newLife=()=>({hunger:0,loneliness:20,confidence:50,influence:0,poison:0,qi:20,deviation:0,wounds:0,loyalty:65,satisfaction:65,grievance:0,partner:null,proposal:null,master:null,disciples:[],arts:[],mastery:{},gear:[],bag:{},study:null,craft:null,travel:null,captive:null,hiddenUntil:0,cooldowns:{},last:-1,petition:null,evidence:[],debts:[],records:[],hobby:'reading',lastDaily:-1,variants:[],loot:null});
X.newGroup=()=>({materials:{herb:0,ore:0,stone:0,wood:0},stockItems:{},library:[],facilities:{forge:0,alchemy:0,clinic:0,dorm:0},damage:0,legitimacy:65,unrest:0,constitution:'council',bloc:[],case:null,lastCouncil:-30,lastChange:-180,policies:{allowTrade:true,law:'fair',training:1},reports:[],contracts:[],intel:{},security:30,missions:[],productionWork:0,lastDaily:-1});
X.initLife=(c,foreign=false)=>{const b=c.mx.brain;b.civil??=X.newLife();return b.civil};
const personInit=N.initPerson;N.initPerson=c=>{personInit(c);if(c.mx.brain)X.initLife(c);return c};
const foreignInit=N.foreignInit;N.foreignInit=(s,f)=>{foreignInit(s,f);for(const r of f.roster)X.initLife(r,true);return f};
const init=N.init;N.init=s=>{init(s);s.patch.civil??={version:1,next:1,groups:{},relations:{},caravans:[],cases:[],history:[],training:{enabled:false,pending:[],samples:[],decisions:0,dropped:0},lastDaily:-1};const q=s.patch.civil;
 for(const c of [...Object.values(s.chars),...s.applicants])X.initLife(c);
 for(const key of ['player',...s.factions.map(f=>f.id)])if(!q.groups[key]){const g=q.groups[key]=X.newGroup();if(key!=='player'){const f=s.factions.find(f=>f.id===key);g.library=Object.values(P.arts).filter(a=>a.source==='public'&&a.paths.includes(f.path)).map(a=>a.id).slice(0,12);}}
 return s;
};
G.MIGRATE[7]=s=>{N.init(s);s.schema=8;s.v=G.VERSION;return s};
const fresh=G.newGame;G.newGame=(...args)=>{const s=fresh(...args);N.init(s);return s};
const person=W.person;W.person=id=>id?person(id):null;
X.life=a=>a.b.civil;X.group=id=>X.state().groups[id];X.activeGroup=id=>id==='player'||G.S.factions.some(f=>f.id===id&&!f.dead);
X.members=id=>W.people().filter(a=>a.group===id);
X.leader=id=>id==='player'?W.person(G.S.sect.leader):W.person(G.S.factions.find(f=>f.id===id&&!f.dead)?.mx.leader);
X.isLeader=a=>X.leader(a.group)?.id===a.id;
X.rank=a=>a.f?(a.id===a.f.mx.leader?4:a.c.mx.role==='ผู้อาวุโส'?3:a.c.mx.role==='ศิษย์อาวุโส'?2:1):a.c.rank;
X.path=a=>a.f?a.f.path:a.c.path;
X.age=a=>(G.S.day-(a.f?a.c.mx.born:a.c.born))/360;
X.health=(a,d=0)=>{if(a.f)a.c.mx.health=C(a.c.mx.health+d,0,100);else a.c.hp=C(a.c.hp+d,0,100);return W.health(a)};
X.fatigue=(a,d=0)=>{if(a.f)a.c.mx.fatigue=C(a.c.mx.fatigue+d,0,100);else a.c.fat=C(a.c.fat+d,0,100);return W.fatigue(a)};
X.stress=(a,d=0)=>{if(a.f)a.c.mx.stress=C(a.c.mx.stress+d,0,100);else a.c.stress=C(a.c.stress+d,0,100);return a.f?a.c.mx.stress:a.c.stress};
X.sat=(a,d=0)=>{const l=X.life(a);if(a.f)l.satisfaction=C(l.satisfaction+d,0,100);else a.c.sat=C(a.c.sat+d,0,100);return a.f?l.satisfaction:a.c.sat};
X.loyalty=(a,d=0)=>{const l=X.life(a);if(a.f)l.loyalty=C(l.loyalty+d,0,100);else a.c.loy=C(a.c.loy+d,0,100);return a.f?l.loyalty:a.c.loy};
X.foundation=(a,d=0)=>{if(a.f)a.c.mx.foundation=C(a.c.mx.foundation+d,0,100);else a.c.found=C(a.c.found+d,0,100);return a.f?a.c.mx.foundation:a.c.found};
X.balance=(group,key)=>{if(group==='player')return G.S.res[key]||0;const f=G.S.factions.find(f=>f.id===group&&!f.dead);if(!f)return 0;return key==='silver'?f.wealth:key==='food'?f.stock:X.group(group).materials[key]||0};
X.add=(group,key,qty,label)=>{if(!Number.isFinite(qty)||X.balance(group,key)+qty< -1e-8)return false;if(group==='player')G.add(key,qty,label||'กิจการสำนัก');else{const f=G.S.factions.find(f=>f.id===group&&!f.dead);if(!f)return false;if(key==='silver')f.wealth=Math.max(0,f.wealth+qty);else if(key==='food')f.stock=Math.max(0,f.stock+qty);else X.group(group).materials[key]=Math.max(0,(X.group(group).materials[key]||0)+qty);}return true};
X.canPay=(group,cost,reserve=true)=>{if(!X.activeGroup(group))return false;if(group==='player'&&reserve&&!N.reserveAllows(cost))return false;return Object.entries(cost).every(([k,v])=>Number.isFinite(v)&&v>=0&&X.balance(group,k)+1e-8>=v)};
X.pay=(group,cost,label,reserve=true)=>{if(!X.canPay(group,cost,reserve))return false;for(const [k,v]of Object.entries(cost))X.add(group,k,-v,label);if(cost.silver)W.state().economy.treasury+=cost.silver;return true};
X.transfer=(from,to,key,qty)=>{if(!X.activeGroup(from)||!X.activeGroup(to)||!Number.isFinite(qty)||qty<=0||X.balance(from,key)<qty)return false;X.add(from,key,-qty,'โอนทรัพยากร');X.add(to,key,qty,'รับโอนทรัพยากร');return true};
X.pairKey=(a,b)=>[a,b].sort().join('|');
X.diplomacy=(a,b)=>{if(a===b)return null;const k=X.pairKey(a,b),q=X.state();if(!q.relations[k]){const f=a==='player'?G.S.factions.find(f=>f.id===b):b==='player'?G.S.factions.find(f=>f.id===a):null;q.relations[k]={a:[a,b].sort()[0],b:[a,b].sort()[1],trust:f?.trust||0,relation:f?.rel||0,alliance:f?.stance==='ally',trade:!!f?.pact,hostility:f?.stance==='war'?80:0,war:f?f.stance==='war':Object.hasOwn(G.S.factions.find(f=>f.id===a)?.war||{},b),since:G.S.day,lastTrade:-30,embargo:false};}return q.relations[k]};
X.war=(a,b)=>!!X.diplomacy(a,b)?.war;
X.knows=(a,id)=>a.group===W.person(id)?.group||a.b.knowledge.some(k=>k.actor===id||k.target===id)||!!a.b.relations[id];
X.knownGroups=a=>[...new Set(a.b.knowledge.map(k=>k.group).filter(k=>k!==a.group&&X.group(k)))];
X.location=a=>X.life(a).captive?.group||X.life(a).travel?.location||W.location(a);
X.present=a=>!!a&&(a.f||a.c.state==='home'||a.c.state==='civilTravel'&&X.life(a).travel?.phase==='stay')&&W.person(a.id)?.c===a.c&&W.health(a)>0&&!X.life(a).captive&&(!X.life(a).travel||X.life(a).travel.phase==='stay');
const location=W.location;W.location=a=>a.b.civil?.captive?.group||a.b.civil?.travel?.location||location(a);
const available=W.available;W.available=a=>!!a&&!!a.b.civil&&!X.life(a).captive&&!X.life(a).study&&((!X.life(a).travel&&available(a))||(X.life(a).travel?.phase==='stay'&&W.health(a)>0));
X.near=(a,t)=>X.present(t)&&X.location(a)===X.location(t);
X.arts=a=>a.f?X.life(a).arts:a.c.mx.arts;
X.mastery=(a,id)=>a.f?X.life(a).mastery[id]||0:a.c.mx.mastery[id]||0;
X.setMastery=(a,id,n)=>{(a.f?X.life(a).mastery:a.c.mx.mastery)[id]=C(n,0,100)};
X.artAccess=(a,id)=>{const d=P.arts[id];if(!d||!d.paths.includes(X.path(a)))return false;if(!a.f)return N.allowedArt(a.c,id)&&!N.artProblems(a.c,d).length;return X.group(a.group).library.includes(id)&&W.realm(a)>=Math.max(0,d.realm-1)&&X.foundation(a)>=(d.foundation||0)&&Object.entries(d.requirements||{}).every(([k,v])=>(k==='spirit'||k==='body'||k==='heart'?a.c.mx.apt:W.attr(a,k))>=v)};
X.learnable=a=>(a.f?X.group(a.group).library:G.S.patch.knownArts).find(id=>!X.arts(a).includes(id)&&X.artAccess(a,id));
X.gear=a=>a.f?X.life(a).gear:G.S.patch.items.filter(i=>i.owner===a.id);
X.weapon=a=>X.gear(a).find(i=>P.items[i.def]?.type==='weapon');
X.gearBonus=a=>X.gear(a).reduce((n,i)=>n+(N.itemStats({...i,grade:P.items[i.def].grade,quality:0,affix:'none'}).atk||0),0);
X.power=a=>{if(!a.f){const u=G.fighter(a.c);return u.hp*u.atk/360}let martial=0;for(const id of X.arts(a))martial+=(P.arts[id]?.tier||0)+X.mastery(a,id)/100;return G.tierPow(W.realm(a))*(.6+X.foundation(a)/100)*(W.health(a)/100)*(1+Math.min(1,X.gearBonus(a))+.03*martial)};
X.honest=a=>a.f?a.f.honor> .45:!N.hasTrait(a.c,'biased')&&W.attr(a,'loy')>=45;
X.result=(a,id,text,target=null,changes={})=>{W.record(a,id,a.name+' '+text,target,changes);const q=X.state();q.history.unshift({day:G.S.day,actor:a.id,group:a.group,action:id,text:(a.name+' '+text).slice(0,600),changes});q.history=q.history.slice(0,100);X.life(a).records.unshift({day:G.S.day,action:id,text:text.slice(0,500)});X.life(a).records=X.life(a).records.slice(0,12);if(['CHALLENGE_AUTHORITY','COUP','REMOVE_LEADER','ASSASSINATE','FORM_ALLIANCE','SIEGE','LEAVE_SECT','MARRY'].includes(id))W.emit(id,a.id,target,a.name+' '+text,{public:true,importance:90,witnesses:X.members(a.group).map(t=>t.id),effects:changes});};
X.destroyPerson=(a,why)=>{if(!a)return;if(!a.f){G.die(a.c,why);return}const f=a.f;X.add(f.id,'silver',a.b.wallet,'ทรัพย์สินผู้จากไป');a.b.wallet=0;f.roster=f.roster.filter(r=>r!==a.c);f.pop=Math.max(0,f.pop-1);f.mx.archive.push({name:a.name,realm:W.realm(a),day:G.S.day,reason:why});f.mx.archive=f.mx.archive.slice(-24);W.emit('MOURN',a.id,null,a.name+' '+why,{importance:90,public:true,witnesses:X.members(f.id).map(t=>t.id)});if(f.mx.leader===a.id){f.mx.leader=f.roster.slice().sort((x,y)=>y.r-x.r)[0]?.mx.id||null;}W.cleanup();};
})(window.G);
