/* 1.4 UI: daily schedules, leader style, world pulse, richer time-skip progress. */
(function(G){'use strict';const U=G.UI,N=G.N,A=U.A,E=U.esc,S=()=>G.S,F=G.f1;
const btn=(text,a,data={},cls='')=>'<button type="button" class="sm '+cls+'" data-a="'+a+'" '+Object.entries(data).map(([k,v])=>'data-'+k+'="'+E(v)+'"').join(' ')+'>'+E(text)+'</button>';
const dim=t=>'<div class="dim">'+t+'</div>',card=(title,body)=>'<section class="card"><h3>'+E(title)+'</h3>'+body+'</section>',row=t=>'<div class="item">'+t+'</div>';
const sel=(id,list,value,a,data={})=>'<select id="'+id+'"'+(a?' data-a="'+a+'"':'')+' '+Object.entries(data).map(([k,v])=>'data-'+k+'="'+E(v)+'"').join(' ')+'>'+list.map(([k,n])=>'<option value="'+E(k)+'"'+(String(k)===String(value)?' selected':'')+'>'+E(n)+'</option>').join('')+'</select>';

N.scheduleHtml=c=>{const l=c.mx.life,mood=l.mood||{},ag=l.agenda||[];return card('ตารางวันนี้ของ '+c.name,dim('อารมณ์: '+(mood.tag==='weary'?'อ่อนล้า':mood.tag==='driven'?'มุ่งมั่น':mood.tag==='lonely'?'เหงา':mood.tag==='agitated'?'กระสับกระส่าย':mood.tag==='content'?'สงบ':'ไม่คงที่')+' • พลัง '+Math.round(mood.energy||0)+' • ใจ '+Math.round(mood.spirit||0))+dim('เป้าหมาย: '+E(N.personalGoal(c)))+dim('งานหลัก '+E(G.JOBS[c.job].n)+' คาบหน้าที่ '+(N.DUTY_SLOTS[c.job]||[]).map(k=>N.SLOT_NAME[k]).join(' / '))+dim('นิสัย: วันส่วนตัวทุก '+(1+(l.habits?.personal||0))+' ของสัปดาห์'+(l.habits?.nightOwl?' • ชอบฝึกค่ำ':'')+(l.habits?.early?' • ตื่นเช้า':''))+(ag.length?'<ol class="day-agenda">'+ag.map(x=>'<li><b>'+E(N.SLOT_NAME[x.slot]||x.slot)+'</b> '+E(N.ACTIVITIES[x.key]||x.key)+(x.status==='skipped'?' (ไม่ได้ทำ)':x.status==='paired'?' (ร่วมกิจกรรม)':'')+dim(E(x.why)+(x.target&&S().chars[x.target]?' • กับ '+E(S().chars[x.target].name):''))+'</li>').join('')+'</ol>':dim('รอประเมินเมื่อเดินเวลา'))+dim('ความหลากหลายวันนี้ '+(l.variety||0)+' กิจกรรม • ไม่ทำซ้ำแบบเดิมทุกวัน'))};

const lives=N.views.lives;N.views.lives=()=>card('ชีวิตจริงรายวัน',dim('แต่ละคนมี 6 ช่วงเวลา: รุ่งอรุณ เช้า เที่ยง บ่าย เย็น ค่ำ เลือกจากบุคลิก หน้าที่ สุขภาพ อากาศ และสิ่งที่เพิ่งทำ'))+lives()+G.alive().filter(c=>U.lifeFilter==='all'||c.path===U.lifeFilter).slice(0,8).map(N.scheduleHtml).join('');

const steward=N.views.steward;N.views.steward=()=>{const st=N.leaderStyle(N.activeLeader()),w=S().patch.worldLife;return steward()+card('บุคลิกผู้บริหารกับของในคลัง',dim(E(N.styleText()))+dim('แนว '+E(st.label)+' เปลี่ยนน้ำหนักการแจกของ คัดคัมภีร์ ขายของซ้ำ แปรวัตถุดิบ และช่วยชุมชน')+dim('ใช้ของตามนิสัยแล้ว '+w.leaderUses+' ครั้ง • ประเมินทางเลือกสะสม '+w.considerations)+['deepLife','leaderUse'].map(key=>row(({deepLife:'จำลองชีวิต 6 ช่วงต่อวัน',leaderUse:'ให้เจ้าสำนักเอาของที่หาได้/เสกให้ไปสร้างประโยชน์ตามนิสัย'}[key])+sel('ld-'+key,[['1','เปิด'],['0','ปิด']],S().patch.management[key]?'1':'0','mxmanage',{key}))).join('')+dim('เคารพการเปิด/ปิดแจกของ งบ เกรด และสำรอง • คัดคัมภีร์อัตโนมัติต้องเปิดการศึกษาและมีวัสดุจริง'))+card('จังหวะโลกที่เดินแล้ว', (w.worldEvents||[]).slice(0,12).map(e=>row('วัน '+e.day+' • '+E(e.text))).join('')||dim('ยังเงียบ — กดเดินเวลาเพื่อให้โลกขยับ'))};

const people=N.views.people;N.views.people=()=>people()+card('โลกภายนอกเดินทุกวัน',dim('คนต่างสำนักมีชีวิตของตัวเอง: พัก ฝึก ค้า เตรียมกำลัง หรือเทศกาล ตามเสบียง ทุน และบทบาทหัวหน้าฝ่าย ไม่ใช่แค่ตัวเลขรบ')+dim('กิจกรรมต่างสำนักสะสม '+S().patch.worldLife.foreignActions));

const home=U.V.home;U.V.home=function(){const w=S().patch.worldLife,st=N.leaderStyle(N.activeLeader());let h=home();h+=card('โลกที่กำลังเดิน',dim('ผู้บริหาร: '+E(N.styleText()))+dim('จำลองชีวิต '+w.actions+' เหตุ • ประเมิน '+w.considerations+' ทางเลือก • ของถูกใช้ตามนิสัย '+w.leaderUses+' ครั้ง')+((w.worldEvents||[])[0]?dim('ล่าสุด: วัน '+w.worldEvents[0].day+' • '+E(w.worldEvents[0].text)):'')+btn('ดูชีวิตสมาชิก','mxnav',{tab:'sect',sub:'lives'})+btn('ดูการตัดสินใจผู้บริหาร','mxnav',{tab:'sect',sub:'steward'}));return h};

const char=U.M.char;U.M.char=id=>{const c=S().chars[id],h=char(id);return c?N.scheduleHtml(c)+h:h};

const origAdv=U.adv;
U.adv=function(n,untilEvent){const s=S();if(U.busy||s.over)return;if(s.pending.length){U.toast('มีเรื่องรอการตัดสินใจ — ดูที่หน้าภาพรวม');U.go('home');return}U.busy=true;U.prog=0;U.renderAdv();const t0=performance.now();G.advance(n,{untilEvent,onProgress:(d,t)=>{U.prog=d/t*100;const e=document.getElementById('advtxt');if(e)e.textContent='จำลองชีวิตสำนัก '+d+'/'+t+' วัน • ประเมิน '+S().patch.worldLife.considerations+' ทางเลือก • '+(S().patch.management.deepLife?'6 ช่วง/วัน':'โหมดย่อ');const b=document.querySelector('#advbar .bar i');if(b)b.style.width=U.prog+'%'}}).then(r=>{U.busy=false;U._keep=1;if(S().day-U.lastAuto>=7){G.save('auto');U.lastAuto=S().day}const ms=Math.round(performance.now()-t0);if(r.alerts&&r.alerts.length)U.toast('หยุดเพราะ: '+r.alerts[0]);else if(r.stopped)U.toast('หยุดตามคำสั่ง (ผ่านไป '+r.done+' วัน)');else U.toast('จำลอง '+r.done+' วัน ใช้เวลา '+ms+' มิลลิวินาที');U.render()})};

U.renderAdv=function(){const s=S();if(U.busy){document.getElementById('advbar').innerHTML='<div style="flex:1"><div class="dim" id="advtxt">กำลังจำลองชีวิตสำนักแบบละเอียด…</div>'+U.bar(U.prog||0)+'</div><button class="warn" data-a="stop">หยุด</button>';return}if(s.over){document.getElementById('advbar').innerHTML='<span class="r">สำนักล่มสลายแล้ว</span> <button data-a="tab" data-t="menu">เมนู</button>';return}
document.getElementById('advbar').innerHTML=[[1,'+1 วัน'],[7,'+7 วัน'],[30,'+30 วัน'],[90,'+90 วัน']].map(a=>'<button class="sm" data-a="adv" data-n="'+a[0]+'">'+a[1]+'</button>').join('')+'<button class="sm pri" data-a="advev">▶ ถึงเหตุสำคัญ</button>'};
})(window.G);
