(function(G){'use strict';const N=G.N,P=G.PATCH;
G.JOBS.study={n:'ศึกษาวิชา',i:'📜'};
N.artCompatible=(c,a)=>!!a&&a.paths.includes(c.path)&&c.realm>=N.needed(c,a.realm)&&(!a.manuals?.length||a.manuals.some(id=>N.manualMatches(c,id)));
N.sources=(c,a)=>{const list=[];if(G.S.patch.knownArts.includes(a.id))list.push({kind:'library',id:'',label:'ม้วนตำรับส่วนกลาง'});if(a.source==='manual'&&a.manuals.some(id=>N.manualMatches(c,id)))list.push({kind:'manual',id:'',label:'บทในคัมภีร์ที่ฝึก'});if(c.mx.signatures.includes(a.id))list.push({kind:'signature',id:'',label:'วิชาประจำตัว'});for(const t of G.alive())if(t.id!==c.id&&N.home(t)&&t.job==='teach'&&!t.mx.study&&!(t.mx.busyUntil>G.S.day)&&t.mx.arts.includes(a.id)&&(t.mx.mastery[a.id]||0)>=60&&N.artCompatible(t,a))list.push({kind:'teacher',id:t.id,label:'อาจารย์ '+t.name});return list};
N.artProblems=(c,a,source=true)=>{const err=[];if(!N.artCompatible(c,a))err.push('มรรคา คัมภีร์ หรือขอบเขตไม่ตรง');for(const[k,v]of Object.entries(a?.requirements||{}))if(N.stat(c,k)<v)err.push(({spirit:'รากปราณ',body:'กายา',heart:'จิตศรัทธา',craft:'ฝีมือช่าง',admin:'บริหาร'}[k]||k)+' ต้อง '+v);if(c.found<(a?.foundation||0))err.push('ฐานรากต้อง '+a.foundation);if(source&&a&&!N.sources(c,a).length)err.push('ยังไม่มีตำรับหรือผู้สอน');return err};
N.unlockArt=(id,source)=>{if(!P.arts[id]||G.S.patch.knownArts.includes(id))return;G.S.patch.knownArts.push(id);G.S.patch.artSources[id]={day:G.S.day,source};N.log('ได้รับตำรับ '+P.arts[id].name,[source],2,'cult')};
N.learn=(cid,id,teacher)=>{const c=G.S.chars[cid],a=P.arts[id];if(!N.home(c)||!a)return 'ผู้เรียนหรือวิชาไม่พร้อม';if(c.mx.study||c.mx.busyUntil>G.S.day)return 'กำลังศึกษาเรื่องอื่น';if(c.mx.arts.includes(id))return 'เรียนแล้ว';const err=N.artProblems(c,a);if(err.length)return err.join(' • ');const source=teacher?N.sources(c,a).find(x=>x.id===teacher&&x.kind==='teacher'):N.sources(c,a)[0];if(!source)return 'ผู้สอนไม่พร้อม';if(!N.pay(a.cost,'ศึกษา '+a.name))return 'ทรัพยากรศึกษาไม่พอ';c.mx.study={id,remaining:a.days,kind:source.kind,teacher:source.id,resumeJob:c.job,resumeFix:c.jobFix};c.job='study';c.jobFix=1;G.bio(c,'เริ่มเรียน '+a.name+' จาก '+source.label);return ''};
N.cancelStudy=cid=>{const c=G.S.chars[cid];if(!N.home(c)||!c.mx.study)return 'ไม่มีการเรียนที่ยกเลิกได้';c.job=c.mx.study.resumeJob;c.jobFix=c.mx.study.resumeFix;c.mx.study=null;return ''};
N.active=(cid,id)=>{const c=G.S.chars[cid];if(!N.home(c)||!c.mx.arts.includes(id))return 'ยังใช้วิชานี้ไม่ได้';if(c.mx.active.includes(id))c.mx.active=c.mx.active.filter(x=>x!==id);else{if(c.mx.active.length>=3)return 'จัดใช้ได้ไม่เกินสามวิชา';if(!N.artCompatible(c,P.arts[id]))return 'คัมภีร์หรือมรรคาไม่ตรง';c.mx.active.push(id)}return ''};
N.researchArt=id=>{const a=P.arts[id];if(!a||a.source!=='scroll'||a.tier>=4)return 'วิชานี้ต้องค้นจากโลกหรือผู้สอน';if(G.S.patch.knownArts.includes(id))return 'มีตำรับแล้ว';if(G.S.fac.library<Math.max(1,a.tier))return 'ห้องตำรับระดับไม่พอ';if(!N.pay({coin:25+a.tier*15,stone:8+a.tier*8},'ค้นคว้าวิชา'))return 'ทรัพยากรไม่พอ';N.unlockArt(id,'ค้นคว้าในห้องตำรับ');return ''};
N.dailyArts=()=>{for(const c of G.alive()){if(!N.home(c))continue;c.mx.buffs=c.mx.buffs.filter(x=>x.until>G.S.day);c.mx.mana=Math.min(N.maxMana(c),c.mx.mana+(c.job==='rest'?4:1));if(c.mx.study&&c.hp>=50&&c.fat<85&&(!N.allowedArt||N.allowedArt(c,c.mx.study.id))){const st=c.mx.study,a=P.arts[st.id];if(!N.artCompatible(c,a))continue;let extra=0;if(st.kind==='teacher'){const t=G.S.chars[st.teacher];if(!t){N.unlockArt(st.id,'บันทึกที่อาจารย์ทิ้งไว้');st.kind='library';st.teacher=''}else{if(!N.home(t)||(t.job!=='teach'&&(!N.privateTeacher||N.privateTeacher(c,st.id)!==t))||t.mx.study||t.mx.busyUntil>G.S.day||!t.mx.arts.includes(st.id)||(t.mx.mastery[st.id]||0)<60)continue;extra=(.35+t.at.int/200)/Math.max(1,G.home().filter(x=>x.mx.study?.teacher===t.id).length);if(t.job!=='teach')extra*=.6;t.fat=Math.min(100,t.fat+.35);G.relAdd(c,t,.1)}}st.remaining-=Math.max(.15,(.6+c.at.int/125)*N.trait(c,'learn')*(1+extra+N.leadership().teaching)*(1-c.fat*.004));c.fat=Math.min(100,c.fat+1.2);if(st.remaining<=0){c.mx.arts.push(st.id);c.mx.mastery[st.id]=25;if(c.mx.active.length<3)c.mx.active.push(st.id);c.job=st.resumeJob;c.jobFix=st.resumeFix;c.mx.study=null;G.bio(c,'เรียนรู้ '+a.name);N.log(c.name+' เรียน '+a.name+' สำเร็จ',['ชำนาญเริ่มต้น 25% ผลวิชาจะเติบโตเมื่อใช้งาน'],2,'cult',[c.id])}}
for(const id of c.mx.active)if(N.artCompatible(c,P.arts[id]))c.mx.mastery[id]=Math.min(100,(c.mx.mastery[id]||25)+.65*N.trait(c,'learn'));
for(const id of c.mx.signatures)if(!c.mx.arts.includes(id)&&!N.artProblems(c,P.arts[id],false).length){c.mx.arts.push(id);c.mx.mastery[id]=60;G.bio(c,'ฟื้นความเข้าใจ '+P.arts[id].name)}
if(!N.planCandidates&&G.S.patch.management.autoStudy&&c.job==='cultivate'&&G.home().filter(x=>x.mx.study).length<Math.max(1,Math.floor(G.home().length/5))&&G.S.res.food>G.home().length*20&&!c.jobFix&&!c.mx.study&&c.hp>=70&&c.fat<50&&G.S.res.silver>G.S.patch.management.reserve+30){const a=Object.values(P.arts).find(a=>a.tier<=1&&!c.mx.arts.includes(a.id)&&!N.artProblems(c,a).length&&N.can(a.cost));if(a)N.learn(c.id,a.id)}}};
const fighter=G.fighter;G.fighter=(c,gear)=>{const u=fighter(c,gear);u.hp*=1+N.bonus(c,'hp')+c.mx.permanentHp/100+(N.hasTrait(c,'dragon')?.15:0);u.atk*=1+N.bonus(c,'atk');u.def*=1+N.bonus(c,'armor');const weapon=P.items[N.owned(c,'weapon')?.def]?.subtype;if(weapon&&c.traits.some(t=>P.traits[t.slice(3)]?.weapon===weapon)){if(weapon==='fan')u.heal*=1.25;else u.atk*=1.2}u.heal+=N.bonus(c,'heal')*6*Math.pow(1.4,c.realm);u.max=u.hp;u.energy=Math.min(c.mx.mana,N.maxMana(c));u.effects=Object.fromEntries(['pierce','guard','burst','control','cleave','drain','counter','regen','shield','weaken'].map(k=>[k,N.bonus(c,k)]));u.baseAtk=u.atk;return u};
N.roundStart=(u,r)=>{if(r>1&&u.burstFactor){u.atk/=u.burstFactor;delete u.burstFactor}if(!u.effects||u.energy<1)return;const e=u.effects;if(r===1){if(e.burst){u.burstFactor=1+e.burst;u.atk*=u.burstFactor}u.ward+=u.max*e.shield}if(e.regen)u.hp=Math.min(u.max,u.hp+u.max*e.regen*.15);if(e.burst||e.shield||e.regen)u.energy=Math.max(0,u.energy-1)};
N.hit=(u,t,dmg,foes)=>{if(u.energy<1||!u.effects)return;const e=u.effects;if(e.drain)u.hp=Math.min(u.max,u.hp+dmg*e.drain);if(e.weaken)t.atk=Math.max(t.atk*.8,t.atk*(1-Math.min(.12,e.weaken*.1)));if(e.control)t.qi=Math.max(0,t.qi-Math.min(1,e.control));if(e.cleave){const other=foes.find(x=>x!==t&&x.hp>0);if(other)other.hp-=dmg*Math.min(.6,e.cleave*.4)}if(t.effects?.counter&&t.energy>0){u.hp-=dmg*Math.min(.5,t.effects.counter*.3);t.energy--}if(Object.values(e).some(x=>x))u.energy=Math.max(0,u.energy-1)};
const aftermath=G.aftermath;G.aftermath=(A,r,label)=>{for(const u of A)if(u.c?.mx)u.c.mx.mana=Math.max(0,u.energy||0);return aftermath(A,r,label)};
})(window.G);
