/* Sonnet remains authoritative. Patch state is additive under S.patch. */
(function(G){'use strict';const P=G.PATCH,N=G.N= {};G.VERSION='1.1.0';G.SCHEMA=2;
N.manualMap=Object.fromEntries(Object.keys(P.manuals).map(id=>[id,'sm_'+id]));
N.legacyManuals={mist:['qi_cloud','qi_ice'],flame:['qi_flame'],jade:['qi_wood'],thunder:[],mountain:['body_turtle'],asura:['body_asura'],river:['body_hawk'],beast:['body_jade'],shelter:['faith_guard'],mercy:['faith_heal'],harvest:['faith_nature'],ancestor:[]};
N.manualMatches=(c,id)=>c.manual===N.manualMap[id]||N.legacyManuals[id]?.includes(c.manual);
for(const[id,d]of Object.entries(P.manuals)){const el={metal:0,wood:1,water:2,fire:3,earth:4}[d.affinity];G.MANUALS['sm_'+id]={p:d.path,n:d.name,d:d.desc,sp:d.speed,bt:-d.risk,cost:d.path==='qi'?{stone:.1*d.cost}:d.path==='body'?{food:.2*d.cost,herb:.08*d.cost}:{},el:[el],rank:d.start?0:1,lore:1,stress:d.path==='body'?d.cost:1,cap:d.role==='guard'?10:0,dom:{safety:'protect',health:'heal',food:'nature',harmony:'protect'}[d.domain],tech:[{r:0,n:'บทพื้นฐาน '+d.name,atk:d.role==='burst'?.25:d.role==='pierce'?.2:0,def:d.role==='guard'?.25:0,heal:d.role==='heal'?.25:0}]};}
N.siteMap={herbwood:'forest',oldmine:'mine',beastvale:'dragon_nest',silkroad:'temple',oldtemple:'ruin',cave:'star_vault',moon:'moon_cave',thunder:'peak'};
// Add the two missing regional routes rather than map several themes onto one pool.
G.LOCS.moon={n:'ถ้ำจันทราเย็น',k:'realm',dist:6,danger:4,rumor:1,d:'ถ้ำเย็นใต้แสงจันทร์ ซ่อนตำรับและวัตถุดิบสายวารี'};G.LOCS.thunder={n:'ยอดเขาทัณฑ์อัสนี',k:'realm',dist:5,danger:3,rumor:1,d:'ยอดเขาที่ปราณอัสนีสะสม เส้นทางสูงชันและมีผู้พิทักษ์'};
N.uid=k=>'mx_'+k+'_'+G.S.nextId++;
N.home=c=>c&&G.S.chars[c.id]===c&&c.state==='home';
N.stat=(c,k)=>({spirit:c.apt.qi,body:c.apt.body,heart:c.apt.faith,craft:c.at.craft,admin:c.at.admin}[k]||0);
N.needed=(c,r)=>Math.round(r*G.PATHS[c.path].realms.length/6);
N.cost=d=>Object.fromEntries(Object.entries(d||{}).map(([k,v])=>[k==='coin'?'silver':k==='medicine'?'pillFound':k,v]));
N.can=d=>G.can(N.cost(d));N.pay=(d,label)=>{const cost=N.cost(d);if(!G.can(cost))return false;G.pay(cost,label);return true};
N.give=(d,label)=>{for(const[k,v]of Object.entries(N.cost(d)))if(G.RES[k])G.add(k,v,label)};
N.log=(text,why=[],p=1,cat='sect',ids=[])=>G.log(p,cat,text,{why,ids});
N.weight=list=>{let r=G.R()*list.reduce((n,x)=>n+x.weight,0);return list.find(x=>(r-=x.weight)<=0)||list.at(-1)};
N.trait=(c,k)=>c.traits.reduce((n,t)=>n*(P.traits[t.slice(3)]?.[k]||1),1);
N.hasTrait=(c,k)=>c.traits.includes('sm_'+k);
const baseTraits={...G.TRAITS};for(const[id,d]of Object.entries(P.traits))G.TRAITS['sm_'+id]={n:d.name,d:d.desc,m:{}};
N.initPerson=c=>{c.mx??={mana:20+4*c.realm,permanentHp:0,permanentMana:0,buffs:[],cooldowns:{},arts:[],active:[],mastery:{},study:null,office:null,exclude:false,legend:null,signatures:[],journal:[],lastRealm:c.realm,lastJob:c.job,goal:{kind:c.path==='faith'?'service':c.at.craft>=70?'craft':'realm',target:c.path==='faith'?90:c.at.craft>=70?5:c.realm+1,done:false},days:{}};return c};
N.init=s=>{s.patch??={items:[],orders:[],knownRecipes:Object.values(P.items).filter(d=>d.theme==='common'&&d.craftable).map(d=>d.id),knownArts:Object.values(P.arts).filter(d=>d.source==='public'||d.source==='scroll'&&d.tier===0).map(d=>d.id),artSources:{},legends:{},stories:{active:[],history:[],cooldowns:{},last:-100},management:{enabled:false,direction:'balanced',admission:'open',target:18,reserve:80,autoEquip:true,autoPills:true,autoStudy:false,autoBuild:true,storyMode:'off',allocation:'equal',maxGrade:2,itemReserve:1,budget:50},offices:{},heir:null,decisions:[],ledger:[],baseline:{...s.res},foreignFollow:[],cheat:false};s.pauseCfg.story??=1;for(const c of [...Object.values(s.chars),...s.applicants])N.initPerson(c);return s};
const mk=G.mkChar;G.mkChar=o=>{const dictionary=G.TRAITS;G.TRAITS=baseTraits;let c;try{c=mk(o)}finally{G.TRAITS=dictionary}if(G.ch(.2))c.traits=[];if(G.ch(.5)){const count=G.ch(.12)?2:1;for(let i=0;i<count;i++){const common=Object.keys(P.traits).filter(id=>!P.traits[id].rare),rare=Object.keys(P.traits).filter(id=>P.traits[id].rare);const id=G.pick(G.ch(.035)?rare:common);if(!c.traits.includes('sm_'+id)&&!(P.traits[id].bodyGroup&&c.traits.some(t=>P.traits[t.slice(3)]?.bodyGroup)))c.traits.push('sm_'+id)}}return N.initPerson(c)};
const newGame=G.newGame;G.newGame=(...args)=>{const s=newGame(...args);N.init(s);s.patch.management.enabled=true;for(const c of G.alive()){c.mx.goal={kind:c.path==='faith'?'service':c.at.craft>=70?'craft':'realm',target:c.path==='faith'?90:c.at.craft>=70?5:c.realm+1,done:false}}s.discovered.moon=1;s.discovered.thunder=1;if(N.addItem){N.addItem('iron_sword',3);N.addItem('root_pill',4);N.addItem('learning_jade',1)}return s};
G.MIGRATE[1]=s=>{N.init(s);s.schema=2;s.v=G.VERSION;return s};
N.training=c=>{let m=N.trait(c,'train')*(N.hasTrait(c,'diligent')?1.15:1)*(N.hasTrait(c,'rootGift')&&c.path==='qi'?2:1);const manual=G.MANUALS[c.manual],match=manual?.el?.includes(c.elem);if(N.hasTrait(c,'heaven'))m*=match?5:3;if(N.hasTrait(c,'yin'))m*=manual?.el?.includes(2)?3:manual?.el?.includes(3)?.8:1;if(N.hasTrait(c,'yang'))m*=manual?.el?.includes(3)?3:manual?.el?.includes(2)?.8:1;if(N.hasTrait(c,'yinyang')&&c.mind>60&&c.fat<60&&manual?.el?.some(x=>x===2||x===3))m*=4;if(N.hasTrait(c,'dragon')&&c.path==='body')m*=4;if(N.hasTrait(c,'hidden')&&c.realm>0)m*=2;return Math.min(8,m)*(1+N.bonus(c,'train'))};
N.bonus=(c,key)=>{let b=0;for(const i of G.S.patch?.items||[])if(i.owner===c.id){const d=P.items[i.def],mult=(1+i.grade*.42)*(1+i.quality*.1);b+=(d.stats[key]||0)*mult+(P.affixes[i.affix]?.stats[key]||0)}for(const buff of c.mx?.buffs||[])if(buff.until>G.S.day&&buff.effect===key)b+=buff.amount;for(const id of c.mx?.active||[]){const a=P.arts[id];if(a&&N.artCompatible?.(c,a)&&a.effect===key&&(!a.weapon||P.items[N.owned?.(c,'weapon')?.def]?.subtype===a.weapon))b+=a.amount*(.5+.5*(c.mx.mastery[id]||25)/100)}return Math.min(3,b)};
const skill=G.skill;G.skill=(c,j)=>Math.min(5,skill(c,j)*N.trait(c,'work')*(1+N.bonus(c,'work')+(j==='craft'?(N.trait(c,'craft')-1)+(N.hasTrait(c,'smith')||N.hasTrait(c,'alchemist')?.2:0)+N.bonus(c,'craft')+N.bonus(c,'smith')/100+N.bonus(c,'alchemy')/100:0)));
const bt=G.btInfo;G.btInfo=(c,m)=>{const o=bt(c,m),b=Math.min(.3,N.bonus(c,'break')+(N.hasTrait(c,'heaven')?.08:0));o.p=G.clamp(o.p+b,.08,.98);if(N.hasTrait(c,'cautious')&&m!=='fast')o.p=G.clamp(o.p+.05,.08,.98);if(b)o.fac.push(['ยุทธภัณฑ์ โอสถ และพรสวรรค์',b]);if(c.mx?.study||c.mx?.busyUntil>G.S.day){o.blk.push('กำลังเรียนวิชาหรือศึกษาเรื่องราว');o.ready=false}return o};
const setJob=G.setJob;G.setJob=(ids,job)=>{if(!G.JOBS[job]&&job!=='auto'||job==='study')return {ok:false,msg:'เลือกงานที่มอบหมายได้'};if(ids.some(id=>{const c=G.S.chars[id];return c?.mx?.study||c?.mx?.busyUntil>G.S.day}))return {ok:false,msg:'ต้องจบหรือยกเลิกการศึกษาก่อนเปลี่ยนงาน'};return setJob(ids,job)};
const patron=G.setPatron;G.setPatron=(c,id)=>{if(c.mx.study||c.mx.busyUntil>G.S.day)return {ok:false,msg:'กำลังศึกษาอยู่'};if(!G.S.villages.some(v=>v.id===id))return {ok:false,msg:'ไม่พบชุมชน'};return patron(c,id)};
const setManual=G.setManual;G.setManual=(c,id)=>c.mx.study||c.mx.busyUntil>G.S.day?{ok:false,msg:'ต้องจบการศึกษาก่อนเปลี่ยนคัมภีร์'}:setManual(c,id);
const sw=G.switchPath;G.switchPath=(c,id)=>c.mx.study||c.mx.busyUntil>G.S.day?{ok:false,msg:'ต้องจบการศึกษาก่อนเปลี่ยนมรรคา'}:sw(c,id);
const die=G.die;G.die=(c,why)=>{if(G.S.patch){for(const i of G.S.patch.items)if(i.owner===c.id)i.owner=null;for(const[k,id]of Object.entries(G.S.patch.offices))if(id===c.id)delete G.S.patch.offices[k];if(G.S.patch.heir===c.id)G.S.patch.heir=null;if(c.mx?.legend)G.S.patch.legends[c.mx.legend].status='dead'}const r=die(c,why);if(G.S.dead[c.id])G.S.dead[c.id].mx={legend:c.mx?.legend,arts:c.mx?.arts?.slice(),journal:c.mx?.journal?.slice(0,12),days:{...c.mx?.days}};return r};
const admit=G.admit;G.admit=id=>{const c=G.S.applicants.find(x=>x.id===id);if(!c)return {ok:false,msg:'ไม่พบผู้สมัคร'};if(G.S.order.length>=G.S.fac.dorm*6)return {ok:false,msg:'ที่พักเต็ม สร้างเรือนพักก่อน'};const saved=c.mx?.legend?{path:c.path,manual:c.manual,realm:c.realm,life:c.life}:null;const r=admit(id);if(r.ok&&!saved)c.mx.goal={kind:c.path==='faith'?'service':c.at.craft>=70?'craft':'realm',target:c.path==='faith'?90:c.at.craft>=70?5:c.realm+1,done:false};if(r.ok&&saved){Object.assign(c,saved);G.S.known[c.manual]=1;G.S.patch.legends[c.mx.legend].status='member';N.log(c.name+' ถ่ายทอดคัมภีร์ส่วนตัวแก่สำนัก',['ผู้สมัครในตำนานนำความรู้จริงมาด้วย'],2,'cult',[c.id])}return r};
N.legend=id=>{const d=P.legends[id],s=G.S;if(!d||s.patch.legends[id]||s.applicants.length>=12)return false;const c=G.mkChar({age:d.age,rank:0,realm:d.realm,path:d.path,bio:d.background});c.name=d.name+(s.names[d.name]?' · ผู้เดินทาง':'');s.names[c.name]=1;c.path=d.path;c.manual=N.manualMap[d.manual];c.realm=d.realm;c.apt={qi:d.stats.spirit,body:d.stats.body,faith:d.stats.heart};c.at={...c.at,int:d.stats.spirit,con:d.stats.body,str:d.stats.body,craft:d.stats.craft,admin:d.stats.admin,cou:78,cau:70,amb:65,loy:85,soc:d.stats.heart,dis:85};c.traits=d.traits.map(t=>'sm_'+t);c.elem={metal:0,wood:1,water:2,fire:3,earth:4}[d.affinity]??2;c.life=G.calcLife(c);c.fee=35;c.day=s.day;c.est={...c.apt};c.mx.lastRealm=c.realm;c.mx.goal={kind:c.path==='faith'?'service':'realm',target:c.path==='faith'?90:c.realm+1,done:false};c.mx.legend=id;c.mx.signatures=d.signatures.slice();s.applicants.push(c);s.patch.legends[id]={person:c.id,status:'applicant',day:s.day};N.log('ผู้เดินทาง '+c.name+' ขอเข้าสำนัก',[d.background],2,'sect',[c.id]);return true};
})(window.G);
