(function(G){'use strict';const N=G.N,P=G.PATCH;
N.offices={deputy:'รองเจ้าสำนัก',training:'ผู้อาวุโสฝ่ายถ่ายทอด',logistics:'ผู้อาวุโสฝ่ายเสบียง',forge:'ผู้อาวุโสฝ่ายหลอม',alchemy:'ผู้อาวุโสฝ่ายโอสถ',community:'ผู้อาวุโสฝ่ายศรัทธา',diplomacy:'ผู้อาวุโสฝ่ายการทูต'};
N.setOffice=(office,id)=>{if(!N.offices[office])return 'ไม่พบหน้าที่';const c=G.S.chars[id];if(id&&(!N.home(c)||c.rank<3||c.id===G.S.sect.leader))return 'ต้องเป็นผู้อาวุโสที่อยู่สำนัก';for(const[k,v]of Object.entries(G.S.patch.offices))if(v===id&&id)delete G.S.patch?.offices[k];if(id)G.S.patch.offices[office]=id;else delete G.S.patch.offices[office];return ''};
N.staff=k=>{const c=G.S.chars[G.S.patch?.offices[k]];return N.home(c)&&!c.mx.study&&!(c.mx.busyUntil>G.S.day)?c:null};
N.leadership=()=>{const c=G.S.chars[G.S.sect.leader];if(!c)return {work:0,teaching:0,fair:0};return {work:Math.min(.15,(c.at.admin+(N.hasTrait(c,'organizer')?20:0))/800),teaching:c.at.int/1000+(N.hasTrait(c,'mentorGift')?.15:0),fair:N.hasTrait(c,'fair')?1:N.hasTrait(c,'biased')?-1:0}};
const sk=G.skill;G.skill=(c,j)=>{const staff={craft:N.staff('forge')||N.staff('alchemy'),farm:N.staff('logistics'),herb:N.staff('logistics'),preach:N.staff('community'),teach:N.staff('training')}[j];return sk(c,j)*(1+N.leadership().work+((staff?.at.admin||0)+(staff&&N.hasTrait(staff,'organizer')?20:0))/1000)};
N.recordDecision=(text,why)=>{const p=G.S.patch;p.decisions.unshift({day:G.S.day,text,why});p.decisions=p.decisions.slice(0,80)};
N.allocate=()=>{const s=G.S,p=s.patch,m=p.management;if(!m.autoEquip&&!m.autoPills)return;let spent=0;const list=G.home().filter(c=>!c.mx.exclude).sort((a,b)=>m.allocation==='talent'?b.apt[b.path]-a.apt[a.path]:m.allocation==='rank'?b.rank-a.rank:m.allocation==='need'?a.hp-b.hp:(a.mx.allocated||0)-(b.mx.allocated||0));for(const c of list){if(m.autoEquip)for(const slot of Object.keys(P.slots)){const old=N.owned(c,slot),oldValue=old?Object.values(N.itemStats(old)).reduce((n,x)=>n+x,0):0;const pool=p.items.filter(i=>!i.owner&&!i.locked&&i.qty>m.itemReserve&&i.grade<=m.maxGrade&&P.items[i.def].type===slot&&!N.equipError(i,c)).sort((a,b)=>Object.values(N.itemStats(b)).reduce((n,x)=>n+x,0)-Object.values(N.itemStats(a)).reduce((n,x)=>n+x,0));const best=pool[0];if(best&&Object.values(N.itemStats(best)).reduce((n,x)=>n+x,0)>oldValue+.01&&spent+P.items[best.def].price<=m.budget){spent+=P.items[best.def].price;N.equip(best.id,c.id);c.mx.allocated=(c.mx.allocated||0)+1}}if(m.autoPills){const effect=c.tox>50?'detox':c.hp<80||c.inj.length?'heal':c.fat>65?'rest':c.mx.mana<N.maxMana(c)*.3?'manaRestore':c.prog>=(G.PATHS[c.path].realms[c.realm]?.need||Infinity)?'break':c.job==='cultivate'?'train':null;const i=p.items.find(i=>!i.owner&&!i.locked&&i.qty>m.itemReserve&&i.grade<=m.maxGrade&&P.items[i.def].effect===effect&&spent+P.items[i.def].price<=m.budget);if(i&&!N.usePill(i.id,c.id)){spent+=P.items[i.def].price;c.mx.allocated=(c.mx.allocated||0)+1}}}if(spent)N.recordDecision('แจกสิ่งของตามนโยบาย '+({equal:'เท่าเทียม',rank:'ตามตำแหน่ง',talent:'ตามพรสวรรค์',need:'ตามความจำเป็น'}[m.allocation]),'ใช้สิ่งของจริงมูลค่า '+spent+' ไม่แตะของล็อกและจำนวนสำรอง')};
N.steward=()=>{const s=G.S,p=s.patch,m=p.management;if(!m.enabled||s.day%7!==1)return;let actions=0;const affordable=cost=>N.can(cost)&&s.res.silver-(N.cost(cost).silver||0)>=m.reserve;const count=s.order.length;
if(s.res.silver<m.reserve&&s.res.food>count*40){const qty=Math.min(60,Math.floor(s.res.food-count*30));if(qty>0){G.trade('food',qty,'sell');N.recordDecision('ขายเสบียงส่วนเกิน '+qty,'หาเงินค่าบำรุงจากผลผลิตจริง เหลืออาหารอย่างน้อยสามสิบวัน')}}if(s.res.food<count*3){for(const k of ['ore','wood','beast','herb']){const qty=Math.min(15,Math.floor(s.res[k]));if(qty>0)G.trade(k,qty,'sell');if(s.res.silver>count*5)break}const qty=Math.min(count*12,Math.floor(s.res.silver/(G.RES.food.p*s.market.food*1.15)));if(qty>0){G.trade('food',qty,'buy');N.recordDecision('ซื้ออาหารฉุกเฉิน '+qty,'ขายทรัพยากรจริงและยอมใช้เงินสำรองเพื่อหลีกเลี่ยงความอดอยาก')}}
// Fill only eligible/vacant posts; preserve player nominations.
for(const [office,id]of Object.entries(p.offices))if(!s.chars[id]||s.chars[id].rank<3)delete p.offices[office];for(const office of Object.keys(N.offices))if(!p.offices[office]){const score=c=>['forge','alchemy'].includes(office)?c.at.craft:office==='training'?c.at.int:office==='community'?c.apt.faith:c.at.admin;const c=G.home().filter(c=>c.rank>=3&&c.rank!==4&&!Object.values(p.offices).includes(c.id)).sort((a,b)=>score(b)-score(a))[0];if(c&&score(c)>=55)N.setOffice(office,c.id)}if(!s.chars[p.heir])p.heir=null;if(!p.heir){const c=G.alive().filter(c=>c.rank>=2&&c.rank!==4&&c.loy>=65).sort((a,b)=>b.at.admin+b.realm*10-a.at.admin-a.realm*10)[0];if(c)p.heir=c.id}
if(m.autoBuild&&!s.buildQ.length){const priorities=[count>=s.fac.dorm*6&&count<m.target?'dorm':null,s.res.food<count*20?'farm':null,m.direction==='learning'?'library':m.direction==='craft'?'forge':m.direction==='community'?'shrine':'garden'];const f=priorities.find(f=>f&&s.fac[f]<G.FAC[f].max);if(f){const cost=Object.fromEntries(Object.entries(G.FAC[f].cost).map(([k,v])=>[k,v*(s.fac[f]+1)]));if(affordable(cost)){const r=G.build(f);if(r.ok){actions++;N.recordDecision('สร้าง '+G.FAC[f].n,'ความจุ/ทิศทางสำนัก และคลังเหนือเงินสำรอง')}}}}
if(actions<2&&count<m.target&&count<s.fac.dorm*6&&s.res.food>count*10){const c=s.applicants.filter(c=>m.admission==='talent'?Math.max(...Object.values(c.apt))>=65:m.admission==='service'?Math.max(c.at.craft,c.at.admin)>=65:true).sort((a,b)=>Math.max(...Object.values(b.apt))-Math.max(...Object.values(a.apt)))[0];if(c&&s.res.silver-c.fee>=m.reserve){const r=G.admit(c.id);if(r.ok){actions++;N.recordDecision('รับ '+c.name,'ผ่านเกณฑ์รับเข้า มีที่พักและเสบียงจริง')}}}
if(actions<2&&s.res.food<count*10&&s.res.silver>m.reserve+30){const qty=Math.min(count*15,Math.floor((s.res.silver-m.reserve)/(G.RES.food.p*s.market.food*1.15)));if(qty>0){G.trade('food',qty,'buy');N.recordDecision('ซื้อเสบียง '+qty,'คลังต่ำกว่าสิบวัน ใช้ตลาด Sonnet และราคาแปรตามปริมาณ');actions++}}
if(actions<2&&m.direction==='craft'&&p.orders.length<2){const id=['root_pill','iron_sword','learning_jade'].find(id=>p.knownRecipes.includes(id)&&N.itemCount(id)<2&&!N.recipeError(id)&&affordable(P.items[id].cost));if(id){N.queue(id);N.recordDecision('ผลิต '+P.items[id].name,'ทิศทางงานช่าง คิวและต้นทุนมีอยู่จริง')}}
s.sect.policies.cultShare={balanced:.55,learning:.7,craft:.4,community:.5}[m.direction];if(s.sect.policies.autoAssign)G.autoAssign();N.allocate();
if(m.storyMode!=='off')for(const e of p.stories.active.slice()){if(s.day<e.ready)continue;const choice=m.storyMode==='decline'?(e.stage?'withdraw':'decline'):e.stage?'safe':'begin';const opt=N.options(e).find(o=>o.id===choice);if(opt&&affordable(opt.cost)){const err=N.storyChoice(e.id,choice);if(!err)N.recordDecision('จัดการเรื่อง '+P.stories[e.def].title,'นโยบาย '+(m.storyMode==='safe'?'วิธีปลอดภัย':'ยุติเรื่อง')+' จ่ายค่าใช้จ่ายจริง ไม่รับบททดสอบรบ')}}};
// Preserve losses of named people from the original combat rules.
const loss=G.fLoss;G.fLoss=(f,n)=>{N.foreignInit(G.S,f);const before=f.roster.slice();loss(f,n);for(const r of before)if(!f.roster.includes(r)){f.mx.archive.push({name:r.n,realm:r.r,day:G.S.day,reason:'สูญเสียจากความขัดแย้ง',...r.mx});f.pop=Math.max(0,f.pop-1)}f.mx.archive=f.mx.archive.slice(-24);N.foreignInit(G.S,f)};
const autoAssign=G.autoAssign;G.autoAssign=()=>{autoAssign();const s=G.S,m=s.patch?.management;if(!m?.enabled)return;const free=G.home().filter(c=>!c.jobFix&&c.rank!==4&&!c.mx.study&&!(c.mx.busyUntil>s.day));for(const c of free)if(c.fat>=65||c.job==='rest'&&c.fat>20||c.hp<55||c.stress>65)c.job='rest';if(s.order.length<8&&G.home().some(c=>c.rank===4&&c.job==='teach'))for(const c of free)if(c.job==='teach')c.job='cultivate';const candidates=()=>free.filter(c=>c.job!=='rest'&&c.hp>=55&&c.fat<65&&c.job!=='preach');const claimed=new Set();const ensure=(job)=>{const assigned=G.home().filter(c=>c.job===job);if(assigned.length){assigned.forEach(c=>claimed.add(c.id));return;}const c=candidates().filter(c=>!claimed.has(c.id)&&['cultivate','guard','hunt','herb','craft','wood','service'].includes(c.job)).sort((a,b)=>G.skill(b,job)-G.skill(a,job))[0];if(c){c.job=job;claimed.add(c.id)}};if(s.res.food<s.order.length*25)ensure('farm');if(s.res.food<s.order.length*3&&!G.home().some(c=>c.job==='farm')){const c=free.filter(c=>!c.mx.study&&!(c.mx.busyUntil>s.day)).sort((a,b)=>b.hp-a.hp)[0]||G.S.chars[G.S.sect.leader];if(N.home(c)&&!c.mx.study&&!(c.mx.busyUntil>s.day))c.job='farm'}const dormCost=G.FAC.dorm.cost.wood*(s.fac.dorm+1),woodTarget=s.order.length>=s.fac.dorm*6&&s.order.length<m.target?dormCost:90;if(s.res.wood<woodTarget)ensure('wood');const silverTarget=m.reserve+G.FAC.dorm.cost.silver*(s.fac.dorm+1)+50;if(s.res.silver<silverTarget)ensure('service');if(s.res.stone<35)ensure('mine');if(s.res.herb<30)ensure('herb');if(s.patch.orders.length)ensure('craft');};
const promote=G.promote;G.promote=(c,d)=>{const r=promote(c,d);c.loy=G.clamp(c.loy,0,100);if(c.rank<3)for(const[k,id]of Object.entries(G.S.patch.offices))if(id===c.id)delete G.S.patch.offices[k];return r};
const succession=G.startSuccession;G.startSuccession=()=>{succession();const p=G.S.pending.find(p=>p.type==='succ'),id=G.S.patch.heir;if(p&&id&&G.S.chars[id]){let o=p.opts.find(o=>o.arg===id);if(!o){const c=G.S.chars[id];o={t:c.name+' · ศิษย์สืบทอดที่แต่งตั้ง',a:'succeed',arg:id}}p.opts=[o,...p.opts.filter(x=>x.arg!==id)].slice(0,4);p.def=0}};
const inj=G.inj;G.inj=(c,sev,why)=>{const r=inj(c,sev,why);c.sat=G.clamp(c.sat,0,100);return r};const punish=G.punish;G.punish=c=>{const r=punish(c);c.sat=G.clamp(c.sat,0,100);c.loy=G.clamp(c.loy,0,100);return r};const reject=G.reject;G.reject=id=>{const c=G.S.applicants.find(c=>c.id===id);if(c?.mx.legend)G.S.patch.legends[c.mx.legend].status='departed';return reject(id)};
const promotion=G.autoPromote;G.autoPromote=()=>{promotion();for(const c of G.alive())if(c.mx?.study||c.mx?.busyUntil>G.S.day){c.job='study';c.jobFix=1}};
const succeed=G.succeed;G.succeed=id=>{const c=G.S.chars[id];if(c?.mx.study){N.cancelStudy(id);G.bio(c,'ยุติการเรียนเพื่อรับหน้าที่เจ้าสำนัก')}for(const e of G.S.patch.stories.active.slice())if(e.actor===id)N.finishStory(e,'closed','ผู้เข้าร่วมรับหน้าที่เจ้าสำนัก');const r=succeed(id);for(const[k,v]of Object.entries(G.S.patch.offices))if(v===id)delete G.S.patch.offices[k];if(G.S.patch.heir===id)G.S.patch.heir=null;for(const c of G.alive()){c.loy=G.clamp(c.loy,0,100);c.sat=G.clamp(c.sat,0,100)}return r};
N.hash=s=>{let h=2166136261;for(const ch of s)h=Math.imul(h^ch.charCodeAt(0),16777619);return h>>>0};
N.foreignInit=(s,f)=>{f.mx??={next:1,archive:[],journal:[],news:null,leader:null};for(const r of f.roster){if(r.mx)continue;const id='fp_'+f.id+'_'+f.mx.next++,h=N.hash(s.seed+'|'+id);r.mx={id,born:s.day-(20+h%35)*360,apt:35+h%50,health:100,fatigue:0,foundation:40+h%25,understanding:35+h%30,progress:0,stress:0,faith:0,lastRealm:r.r,master:null,memories:[[s.day,'เริ่มติดตามจากประชากรเดิมของฝ่าย']],traits:[['รอบคอบ','ขยัน','ทะเยอทะยาน','เมตตา'][h%4]],goal:'เติบโตและรับผิดชอบงานของฝ่าย',role:'ศิษย์'};}
if((!f.mx.leader||!f.roster.some(r=>r.mx.id===f.mx.leader))&&f.roster.length){f.mx.leader=f.roster[0].mx.id;f.roster[0].mx.role='หัวหน้าผู้แทน'}for(const r of f.roster)if(!r.mx.master){const elder=f.roster.find(x=>x!==r&&x.r>r.r);if(elder)r.mx.master=elder.mx.id}};
N.news=f=>{N.foreignInit(G.S,f);f.mx.news={day:G.S.day,source:f.stance==='ally'?'ผู้แทนพันธมิตร':f.pact?'พ่อค้าคู่สัญญา':'ข่าวสาธารณะ',people:JSON.parse(JSON.stringify(f.roster)),archive:JSON.parse(JSON.stringify(f.mx.archive.slice(-12))),leader:f.mx.leader}};
N.foreignDay=()=>{const s=G.S;for(const f of s.factions){N.foreignInit(s,f);const mx=f.mx;if(f.dead){mx.archive=mx.archive.concat(f.roster.map(r=>({name:r.n,realm:r.r,day:s.day,reason:'ฝ่ายล่มสลาย',...r.mx}))).slice(-24);f.roster=[];mx.leader=null;continue}for(const r of f.roster.slice()){const c=r.mx;c.lastRealm??=r.r;if(c.lastRealm!==r.r){c.memories.push([s.day,'ฝ่ายใช้ทุนพัฒนาขอบเขต '+c.lastRealm+' → '+r.r]);c.memories=c.memories.slice(-16);c.lastRealm=r.r}if(c.master&&!f.roster.some(x=>x.mx.id===c.master))c.master=null;const path=G.PATHS[f.path],life=path.life+path.realms.slice(0,Math.min(r.r,path.realms.length)).reduce((n,x)=>n+x.life,0);if((s.day-c.born)/360>life&&G.ch(.008)){f.roster=f.roster.filter(x=>x!==r);f.pop=Math.max(0,f.pop-1);mx.archive.push({name:r.n,realm:r.r,day:s.day,reason:'สิ้นอายุขัย',...c});mx.archive=mx.archive.slice(-24);if(mx.leader===c.id){const next=f.roster.slice().sort((a,b)=>b.r-a.r)[0];mx.leader=next?.mx.id||null;if(next){next.mx.role='หัวหน้าผู้แทน';mx.journal.push({day:s.day,text:next.n+' รับตำแหน่งหลัง '+r.n+' จากไป'})}}continue}
const need=path.realms[Math.min(r.r,path.realms.length-1)].need;if(r.r>=path.realms.length)continue;if(c.health<70||c.fatigue>75||c.stress>75){c.fatigue=Math.max(0,c.fatigue-5);c.stress=Math.max(0,c.stress-4);c.health=Math.min(100,c.health+1);continue}const cost=.08+.03*r.r;if(f.wealth<cost+15)continue;f.wealth-=cost;if(f.path==='body'){if(f.stock<.2)continue;f.stock-=.2;c.stress+=1.8;c.fatigue+=.5}else if(f.path==='faith'){const finite=Math.min(2,f.pop/(30*Math.max(1,f.roster.length)));c.faith=Math.min(180,c.faith+finite);if(c.faith<30)continue;c.faith-=.7}c.progress=Math.min(need,c.progress+(c.apt/65)*.65);c.foundation=Math.min(95,c.foundation+.008);c.understanding=Math.min(95,c.understanding+.006);if(c.progress>=need&&c.foundation>45+r.r*3&&c.understanding>40+r.r*3&&f.wealth>50*Math.pow(1.8,r.r)){const paid=50*Math.pow(1.8,r.r);f.wealth-=paid;if(G.R()<.55+c.apt/300-r.r*.04){r.r++;c.lastRealm=r.r;c.progress=0;c.memories.push([s.day,'ทะลวงสำเร็จด้วยทุนของฝ่าย '+Math.round(paid)]);mx.journal.push({day:s.day,text:r.n+' ก้าวสู่ตำแหน่งขอบเขต '+r.r})}else{c.progress*=.75;c.health=Math.max(40,c.health-10);c.memories.push([s.day,'ทะลวงไม่ผ่าน ใช้เงินทุนและต้องพัก'])}c.memories=c.memories.slice(-16)}}mx.journal=mx.journal.slice(-24);if(!mx.news||s.day%(f.detail?30:90)===0)N.news(f)}};
const rel=G.relAdd;G.relAdd=(a,b,v)=>rel(a,b,v>0?v*Math.sqrt(N.trait(a,'social')*N.trait(b,'social')):v);
const dip=G.dip;G.dip=(id,act,arg)=>{const r=dip(id,act,arg);const f=G.S.factions.find(f=>f.id===id);if(r.ok&&f&&act==='gift'&&N.staff('diplomacy')&&N.hasTrait(N.staff('diplomacy'),'diplomat')){f.rel=Math.min(100,f.rel+1.5);f.trust=Math.min(100,f.trust+.5)}if(r.ok&&f?.mx&&['scout','trade','ally'].includes(act))N.news(f);return r};
N.livesDay=()=>{const s=G.S;for(const c of G.alive()){const worked=c.mx.workedJob;if(worked)c.mx.days[worked]=(c.mx.days[worked]||0)+1;if(c.realm!==c.mx.lastRealm){c.mx.journal.unshift({day:s.day,text:'ขอบเขต '+c.mx.lastRealm+' → '+c.realm+' จากการบ่มเพาะจริง'});c.mx.lastRealm=c.realm}if(s.day%7===0&&worked){const voice={cultivate:'train',study:'study',preach:'preach',craft:'craft'}[worked]||worked,list=P.lifeVoices[voice];c.mx.journal.unshift({day:s.day,text:list?list[N.hash(c.id+'|'+s.day)%list.length]:'รับผิดชอบ '+(G.JOBS[worked]?.n||'งาน')+' ตามหน้าที่'});}const goal=c.mx.goal;if(!goal.done&&((goal.kind==='realm'&&c.realm>=goal.target)||(goal.kind==='craft'&&(c.mx.crafted||0)>=goal.target)||(goal.kind==='service'&&(c.mx.days.preach||0)>=goal.target))){goal.done=true;c.sat=Math.min(100,c.sat+3);c.loy=Math.min(100,c.loy+1);c.mx.journal.unshift({day:s.day,text:'บรรลุเป้าหมายส่วนตัวจากผลงานจริง'});}c.mx.journal=c.mx.journal.slice(0,24);if(s.day%30===0)c.sat=G.clamp(c.sat+N.leadership().fair-(N.hasTrait(c,'ambitious')&&c.realm>=c.rank+2?2:0)-(N.hasTrait(c,'proud')&&c.rank>=3&&c.job==='service'?2:0),0,100)}
if(s.day%30===0){const net=Object.fromEntries(Object.entries(s.res).map(([k,v])=>[k,Math.round((v-(s.patch.baseline[k]||0))*10)/10]));s.patch.ledger.unshift({day:s.day,net,members:s.order.length});s.patch.ledger=s.patch.ledger.slice(0,36);s.patch.baseline={...s.res}}};
const daily=G.stepDay;G.stepDay=()=>{if(G.S.over)return;G.S.alerts=[];N.init(G.S);for(const c of G.alive()){if(c.mx.busyUntil&&G.S.day>=c.mx.busyUntil&&c.mx.storyResume){c.job=c.mx.storyResume.job;c.jobFix=c.mx.storyResume.fix;delete c.mx.storyResume;delete c.mx.busyUntil}c.mx.workedJob=N.home(c)?c.job:null;if(N.hasTrait(c,'dragon')&&N.home(c)){if(G.S.res.food>=.5)G.add('food',-.5,'อาหารบำรุงสายเลือดมังกร');else c.fat=Math.min(100,c.fat+1)}if(N.home(c)){const mount=N.owned(c,'mount');if(mount){const cost=P.items[mount.def].upkeep;c.mx.mountUnfed=!!cost&&!N.can(cost);if(cost&&!c.mx.mountUnfed)N.pay(cost,'ดูแลพาหนะ');else if(cost)c.sat=Math.max(0,c.sat-.05)}}}daily();N.dailyArts();N.dailyStories();N.foreignDay();N.livesDay();N.steward();for(const c of G.alive())for(const k of ['hp','fat','mind','sat','loy','found','tox'])c[k]=G.clamp(c[k],0,100);for(const i of G.S.patch.items)if(i.owner&&!G.S.chars[i.owner])i.owner=null;N.merge();for(const[k,id]of Object.entries(G.S.patch.offices))if(!G.S.chars[id]||G.S.chars[id].rank<3)delete G.S.patch?.offices[k];if(!G.S.chars[G.S.patch.heir])G.S.patch.heir=null;for(const[id,r]of Object.entries(G.S.patch.legends))if(!G.S.chars[r.person]&&!G.S.applicants.some(c=>c.id===r.person))r.status=G.S.dead[r.person]?'dead':'departed'};
})(window.G);
