/* Persistent goals, finite knowledge and contextual planning. No language model/network. */
(function(G){'use strict';const N=G.N,P=G.PATCH,C=G.clamp,W=G.WORLD={};
G.VERSION='2.0.0';G.SCHEMA=7;
W.QUALITY={LOW:{interval:5,memories:24,knowledge:20,events:160,trace:30},NORMAL:{interval:3,memories:40,knowledge:32,events:240,trace:60},DEEP:{interval:1,memories:64,knowledge:48,events:360,trace:100}};
W.DIMS=['affection','trust','respect','fear','rivalry','jealousy','gratitude','debt','loyalty','hatred'];
W.newBrain=()=>({goals:[],goalHistory:[],memories:[],knowledge:[],relations:{},wallet:0,needs:{},tier:2,lastReview:-99,nextDecision:0,lastAction:-1,counts:{},month:{},months:[],trace:[],travel:null,focus:null,plan:null,baseline:null,cohort:null,rumorAt:-99});
const ip=N.initPerson;N.initPerson=c=>{ip(c);c.mx.brain??=W.newBrain();return c};
const fi=N.foreignInit;N.foreignInit=(s,f)=>{fi(s,f);for(const r of f.roster)r.mx.brain??=W.newBrain();f.mx.organization??={lastReview:-7,plan:'survive',history:[],morale:65,cohesion:70,fortification:0,production:0,library:0,warSince:null,invested:0,allowance:0};return f};
const ini=N.init;N.init=s=>{ini(s);s.patch.simulation??={quality:'DEEP',debug:false,next:1,events:[],reports:[],metrics:{decisions:0,candidates:0,success:0,rejected:0,goalsCompleted:0,goalsFailed:0,rumors:0,transfers:0},economy:{routeSafety:1,scarcity:1,medicinePrice:1,herbSupply:40,oreSupply:50,treasury:0,lastDay:-1},observation:null,policy:null,lastDay:-1};for(const f of s.factions)N.foreignInit(s,f);return s};
G.MIGRATE[6]=s=>{N.init(s);s.schema=7;s.v=G.VERSION;return s};
const fresh=G.newGame;G.newGame=(...a)=>{const s=fresh(...a);N.init(s);W.observe(true);return s};
W.state=()=>G.S.patch.simulation;W.config=()=>W.QUALITY[W.state().quality];
W.people=()=>[...G.alive().map(c=>({id:c.id,name:c.name,c,b:c.mx.brain,f:null,group:'player'})),...G.S.factions.filter(f=>!f.dead).flatMap(f=>f.roster.filter(r=>r.mx).map(r=>({id:r.mx.id,name:r.n,c:r,b:r.mx.brain,f,group:f.id})))];
W.person=id=>{const c=G.S.chars[id];if(c)return {id,name:c.name,c,b:c.mx.brain,f:null,group:'player'};for(const f of G.S.factions)if(!f.dead){const c=f.roster.find(r=>r.mx?.id===id);if(c)return {id,name:c.n,c,b:c.mx.brain,f,group:f.id}}return null};
W.realm=a=>a.f?a.c.r:a.c.realm;W.health=a=>a.f?a.c.mx.health:a.c.hp;W.fatigue=a=>a.f?a.c.mx.fatigue:a.c.fat;
W.attr=(a,key)=>a.f?({amb: a.c.mx.traits.includes('ทะเยอทะยาน')?85:45,cau:a.c.mx.traits.includes('รอบคอบ')?85:45,dis:a.c.mx.traits.includes('ขยัน')?85:50,cou:45+a.f.aggr*40,int:a.c.mx.understanding,soc:a.c.mx.traits.includes('เมตตา')?80:50,loy:60,craft:a.c.mx.apt}[key]??50):a.c.at[key]??50;
W.progress=a=>a.f?a.c.mx.progress:a.c.prog;W.need=a=>G.PATHS[a.f?a.f.path:a.c.path].realms[W.realm(a)]?.need||Infinity;
W.available=a=>!!a&&(a.f?(!a.f.dead&&a.f.roster.includes(a.c)):N.home(a.c)&&!a.c.mx.study&&!(a.c.mx.busyUntil>G.S.day))&&!a.b.travel;
W.location=a=>a.b.travel?a.b.travel.location:a.group;
W.tier=a=>a.f?(a.id===a.f.mx.leader?1:a.f.detail||a.f.pact||a.f.stance==='war'?2:3):a.c.id===G.S.sect.leader||a.c.rank>=2||a.c.master||a.c.mx.apprentice.history.length||a.c.mx.legend?1:2;
W.rel=(a,id)=>{if(!a.b.relations[id]){if(Object.keys(a.b.relations).length>=24){const keys=Object.keys(a.b.relations).sort((x,y)=>Math.abs(a.b.relations[x].trust)+a.b.relations[x].rivalry-(Math.abs(a.b.relations[y].trust)+a.b.relations[y].rivalry));delete a.b.relations[keys[0]]}const v=a.f?(a.c.mx.bonds?.[id]||0):(a.c.rel[id]||0);a.b.relations[id]=Object.fromEntries(W.DIMS.map(k=>[k,['affection','trust','respect'].includes(k)?C(v*.6,-100,100):0]))}return a.b.relations[id]};
W.relate=(a,id,delta)=>{if(!a||!id||a.id===id)return;const r=W.rel(a,id);for(const [k,v]of Object.entries(delta))if(W.DIMS.includes(k))r[k]=C(r[k]+v,-100,100)};
W.remember=(a,e,emotion=0)=>{if(!a||a.b.memories.some(m=>m.event===e.id&&m.type===e.keyword))return;const cfg=W.config();a.b.memories.push({event:e.id,type:e.keyword,actor:e.actor,target:e.target,location:e.location,day:e.day,emotion:C(emotion,-100,100),importance:e.importance,confidence:1,decay:e.importance>=80?0:.997,relationshipEffect:emotion,name:e.name,text:e.text});a.b.memories.sort((x,y)=>y.importance-x.importance||y.day-x.day);a.b.memories=a.b.memories.slice(0,cfg.memories)};
W.learn=(a,e,source='direct',confidence=1,claim=null)=>{if(!a)return;const b=a.b,old=b.knowledge.find(x=>x.event===e.id);if(old){if(confidence>old.confidence){old.confidence=confidence;old.source=source;old.claim=claim||e.text;old.verified=source==='direct'||source==='report'}return}b.knowledge.unshift({event:e.id,type:e.keyword,actor:e.actor,target:e.target,group:e.group,location:e.location,day:e.day,heard:G.S.day,confidence,verified:source==='direct'||source==='report',source,claim:(claim||e.text).slice(0,1200),name:e.name});b.knowledge=b.knowledge.slice(0,W.config().knowledge)};
W.emit=(keyword,actor,target,text,opt={})=>{const s=G.S;if(!s.patch?.simulation)return null;const q=W.state();const a=W.person(actor),t=W.person(target);const e={id:'we'+q.next++,day:s.day,keyword,actor:actor||null,target:target||null,group:opt.group||a?.group||t?.group||'player',location:opt.location||a?.group||t?.group||'player',name:a?.name||opt.name||s.sect.name,text:String(text).slice(0,600),importance:opt.importance??40,public:!!opt.public,truth:true,parent:opt.parent||null,effects:opt.effects||{}};q.events.push(e);{const limit=W.config().events,major=q.events.filter(x=>x.importance>=55).slice(-Math.floor(limit*2/3)),minor=q.events.filter(x=>x.importance<55).slice(-Math.ceil(limit/3));q.events=[...major,...minor].sort((x,y)=>x.day-y.day||Number(x.id.slice(2))-Number(y.id.slice(2)));}const witnesses=opt.witnesses||[actor,target].filter(Boolean);for(const id of new Set(witnesses)){const p=W.person(id);if(p){W.learn(p,e);W.remember(p,e,id===target?opt.emotion||0:0)}}return e};
W.spread=()=>{const s=G.S,q=W.state(),people=W.people();for(const a of people){const peers=people.filter(t=>t!==a&&t.group===a.group&&W.location(t)===W.location(a));if((s.day+N.hash(a.id))%(a.b.tier===3?7:3)!==0||!peers.length)continue;const t=peers[(s.day+N.hash(a.id+'news'))%peers.length];const known=new Set(a.b.knowledge.map(x=>x.event));const message=t.b.knowledge.find(k=>k.source!=='hidden'&&!known.has(k.event)&&s.day-k.day<=90);if(message){const e=q.events.find(e=>e.id===message.event);if(e){const distortion=N.hash(a.id+'|'+e.id)%7===0&&!message.verified;const trust=W.rel(a,t.id).trust;W.learn(a,e,'conversation',C(message.confidence*(.78+Math.max(-30,trust)/300),.15,.95),distortion?'ข่าวเล่าต่อที่อาจเกินจริง: '+message.claim.replace(/\d+/g,n=>String(Math.min(999999,+n*2))):message.claim);q.metrics.rumors++}}const report=q.events.find(e=>e.public&&e.day<s.day&&!known.has(e.id)&&(e.group===a.group||s.day-e.day>=(a.f?7:4)));if(report)W.learn(a,report,report.group===a.group?'report':'merchant',report.group===a.group?1:.6)} };
W.needs=a=>{const s=G.S,b=a.b,knownThreat=b.knowledge.some(k=>['DECLARE_WAR','LOSE_DUEL','BECOME_JEALOUS'].includes(k.type)&&s.day-k.heard<60),income=b.wallet<10?80:b.wallet<40?45:10,foundation=a.f?a.c.mx.foundation:a.c.found;return b.needs={healing:C((100-W.health(a))*1.4+W.fatigue(a)*.6,0,100),wealth:income,cultivation:C(35+W.attr(a,'amb')*.4+(W.progress(a)>=W.need(a)?15:0),0,100),martial:C(30+W.attr(a,'cou')*.4,0,100),safety:knownThreat?70:20,social:C(60-W.attr(a,'soc')*.3+(a.f?a.c.mx.stress:a.c.stress)*.3,0,100),recognition:W.attr(a,'amb'),knowledge:C(45+(100-foundation)*.4,0,100),revenge:Math.max(0,...Object.values(b.relations).map(r=>r.hatred+r.rivalry*.3)),loyalty:a.f?W.rel(a,a.f.mx.leader).loyalty:a.c.loy}};
W.GOALS={recover:{name:'ฟื้นร่างกายก่อนกลับไปฝึก',horizon:'short',actions:['RECOVER','REST','CARE_FOR_INJURED'],days:45},wealth:{name:'เก็บเงินซื้อของที่จำเป็น',horizon:'short',actions:['EARN_MONEY','SAVE_MONEY','BUY_ITEM'],days:60},realm:{name:'ก้าวข้ามขอบเขตปัจจุบัน',horizon:'medium',actions:['PREPARE_BREAKTHROUGH','REFLECT','REQUEST_GUIDANCE','MEDITATE','SECLUDED_CULTIVATION','CULTIVATION_EXCHANGE'],days:360},art:{name:'เรียนวิชาที่เข้ากับมรรคา',horizon:'medium',actions:['STUDY_TECHNIQUE','TEACH_DISCIPLE','READ','REQUEST_GUIDANCE','TRAIN_MARTIAL_ART'],days:180},status:{name:'สร้างผลงานให้สมตำแหน่งที่สูงขึ้น',horizon:'long',actions:['HELP_PERSON','GUIDE_JUNIOR_CULTIVATION','HARVEST_RESOURCE','REQUEST_PROMOTION','SUPPORT_CANDIDATE','HOLD_MEETING'],days:720},protect:{name:'ปกป้องคนและสำนักที่ผูกพัน',horizon:'long',actions:['PATROL','CARE_FOR_INJURED','HELP_PERSON','GUIDE_JUNIOR_CULTIVATION','HARVEST_RESOURCE'],days:720},peace:{name:'รักษามิตรภาพและชีวิตสงบ',horizon:'long',actions:['SOCIALIZE','REPAIR_RELATIONSHIP','REPAY_FAVOR','RELAX'],days:720},revenge:{name:'เตรียมตัวท้าประลองคู่ปรับอีกครั้ง',horizon:'medium',actions:['RECOVER','TRAIN_MARTIAL_ART','SECLUDED_CULTIVATION','SEEK_BETTER_WEAPON','CHALLENGE'],days:180},rumor:{name:'ตรวจข่าวก่อนเสี่ยงเดินทาง',horizon:'short',actions:['VERIFY_INFORMATION','TRAVEL','SEARCH_RUINS','RETURN_HOME'],days:60}};
W.addGoal=(a,kind,target=null)=>{if(a.b.goals.some(g=>g.kind===kind&&g.target===target))return;const d=W.GOALS[kind],s=G.S;if(a.b.goals.length>=6)return;const base=kind==='realm'?W.realm(a):kind==='status'?(a.f?a.c.r:a.c.rank):kind==='art'?(a.f?0:a.c.mx.arts.length):a.b.wallet;const g={id:'g'+W.state().next++,kind,target,horizon:d.horizon,created:s.day,due:s.day+d.days,priority:50,progress:0,base,steps:[],cursor:0,attempts:0};g.steps=W.goalPlan(a,g);a.b.goals.push(g);W.emit('SET_GOAL',a.id,target,a.name+' ตั้งใจ'+d.name,{importance:25})};
W.finishGoal=(a,g,result)=>{a.b.goals=a.b.goals.filter(x=>x!==g);a.b.goalHistory.unshift({day:G.S.day,kind:g.kind,result,target:g.target,progress:g.progress});a.b.goalHistory=a.b.goalHistory.slice(0,16);if(result==='complete')W.state().metrics.goalsCompleted++;else W.state().metrics.goalsFailed++;W.emit(result==='complete'?'COMPLETE_GOAL':result==='abandoned'?'ABANDON_GOAL':'FAIL_GOAL',a.id,g.target,a.name+' '+(result==='complete'?'บรรลุ':result==='abandoned'?'วางมือจาก':'ยังไม่สำเร็จตามกำหนด')+'เป้าหมาย '+W.GOALS[g.kind].name,{importance:result==='complete'?65:45,emotion:result==='complete'?8:-8});};
W.goalPlan=(a,g)=>{const n=a.b.needs;switch(g.kind){case'recover':return ['RECOVER','REFLECT'];case'wealth':return a.b.wallet<30?['EARN_MONEY','SAVE_MONEY','BUY_ITEM']:['SAVE_MONEY'];case'realm':return n.healing>55?['RECOVER','REFLECT','REQUEST_GUIDANCE','PREPARE_BREAKTHROUGH']:W.progress(a)>=W.need(a)?['REFLECT','REQUEST_GUIDANCE','PREPARE_BREAKTHROUGH']:['CULTIVATION_EXCHANGE','SECLUDED_CULTIVATION','REFLECT','PREPARE_BREAKTHROUGH'];case'art':return ['REQUEST_GUIDANCE','READ','STUDY_TECHNIQUE','TRAIN_MARTIAL_ART'];case'status':return ['HELP_PERSON','HARVEST_RESOURCE','TRAIN_MARTIAL_ART','REQUEST_PROMOTION'];case'protect':return ['PATROL','CARE_FOR_INJURED','GUIDE_JUNIOR_CULTIVATION'];case'peace':return ['REPAIR_RELATIONSHIP','REPAY_FAVOR','SOCIALIZE'];case'revenge':return [...(n.healing>55?['RECOVER']:[]),'TRAIN_MARTIAL_ART',...(W.weapon(a)?['SEEK_BETTER_WEAPON']:[]),'CHALLENGE'];case'rumor':return ['VERIFY_INFORMATION','TRAVEL','SEARCH_RUINS','RETURN_HOME'];default:return []}};
W.review=a=>{const b=a.b,s=G.S,n=W.needs(a);b.tier=W.tier(a);if(s.day-b.lastReview<(b.tier===1?3:b.tier===2?7:14)&&b.goals.length)return;b.lastReview=s.day;
for(const g of b.goals.slice()){let done=false;switch(g.kind){case'recover':g.progress=C((W.health(a)-50)/45,0,1);done=W.health(a)>=95&&W.fatigue(a)<40;break;case'wealth':g.progress=C(b.wallet/30,0,1);done=b.wallet>=30;break;case'realm':g.progress=W.realm(a)>g.base?1:C(W.progress(a)/W.need(a),0,.95);done=W.realm(a)>g.base;break;case'art':done=!a.f&&a.c.mx.arts.length>g.base;g.progress=done?1:a.c.mx?.study?.remaining? .5:0;break;case'status':done=(a.f?a.c.r:a.c.rank)>g.base;g.progress=C((a.f?0:a.c.merit||0)/50,0,.9);break;case'revenge':if(!W.person(g.target)){W.finishGoal(a,g,'abandoned');continue}done=b.memories.some(m=>m.type==='WIN_DUEL'&&m.target===g.target&&m.day>=g.created);break;case'rumor':done=b.memories.some(m=>m.type==='FIND_TREASURE'&&m.day>=g.created);break;case'peace':done=Object.values(b.relations).some(r=>r.trust>45&&r.affection>40);break;case'protect':done=(b.counts.PATROL||0)+(b.counts.CARE_FOR_INJURED||0)>20;break}if(done){W.finishGoal(a,g,'complete');continue}if(s.day>=g.due){W.finishGoal(a,g,'failed');continue}const steps=W.goalPlan(a,g);if(!g.steps.length||g.steps[0]==='RECOVER'&&steps[0]!=='RECOVER'||steps[0]==='RECOVER'&&g.steps[0]!=='RECOVER'){g.steps=steps;g.cursor=0;}g.priority=({recover:n.healing,wealth:n.wealth,realm:n.cultivation,art:n.knowledge,status:n.recognition,protect:n.safety+W.attr(a,'loy')*.4,peace:n.social,revenge:n.revenge,rumor:60}[g.kind]||40);}
if(n.healing>55)W.addGoal(a,'recover');if(n.wealth>50)W.addGoal(a,'wealth');if(W.realm(a)<G.PATHS[a.f?a.f.path:a.c.path].realms.length)W.addGoal(a,'realm');if(!a.f&&!a.c.mx.arts.length)W.addGoal(a,'art');const ambition=W.attr(a,'amb');W.addGoal(a,ambition>65?'status':W.attr(a,'loy')>65?'protect':'peace');const rival=Object.entries(b.relations).filter(([id,r])=>r.rivalry>25&&r.hatred>8&&W.person(id)).sort((x,y)=>y[1].rivalry-x[1].rivalry)[0];if(rival)W.addGoal(a,'revenge',rival[0]);if(!a.f&&b.knowledge.some(k=>k.type==='LEARN_RUMOR'&&!k.verified))W.addGoal(a,'rumor');b.goals.sort((x,y)=>y.priority-x.priority||x.created-y.created);b.focus=b.goals[0]?.kind||null;b.plan=b.goals[0]?{goal:b.goals[0].id,steps:b.goals[0].steps.slice(b.goals[0].cursor),since:s.day}:null;};
W.score=(a,x)=>{const id=x.id||N.actionId(x.key),r=G.ACTIONS[id],n=a.b.needs;let goal=0;for(const g of a.b.goals){if(W.GOALS[g.kind].actions.includes(id)){goal=Math.max(goal,g.priority*.35);if(g.steps[g.cursor]===id)goal+=18}}const target=x.target&&W.person(x.target),rel=target?W.rel(a,target.id):null;let social=rel?(['SOCIALIZE','CULTIVATION_EXCHANGE','REQUEST_GUIDANCE','CARE_FOR_INJURED','REPAY_FAVOR','BUILD_TRUST'].includes(id)?rel.trust*.1+rel.gratitude*.1-rel.hatred*.15:id==='CHALLENGE'?rel.rivalry*.2+rel.hatred*.1:0):0;const risk=(r?.risk||0)*(W.attr(a,'cau')/100)+(100-W.health(a))*.03*(r?.risk||0);let need=['RECOVER','REST','SLEEP'].includes(id)?n.healing*.25:['EARN_MONEY','SAVE_MONEY'].includes(id)?n.wealth*.25:['SOCIALIZE','REPAIR_RELATIONSHIP'].includes(id)?n.social*.15:0;const recent=a.b.trace.slice(0,8).filter(t=>t.action===id).length*10;const memory=a.b.memories.filter(m=>m.target===x.target&&m.importance>50).slice(0,4).reduce((v,m)=>v+(id==='CHALLENGE'?Math.max(0,-m.emotion)*.08:['REPAY_FAVOR','CARE_FOR_INJURED'].includes(id)?Math.max(0,m.emotion)*.08:0),0);const score=(x.score||0)+goal+social+need+memory-risk-recent;return {...x,id,score,reasons:{base:x.score||0,goal,relationship:social,need,memory,risk,repetition:recent},why:x.why+' • '+(a.b.focus?W.GOALS[a.b.focus].name:'ประเมินสภาพปัจจุบัน')};};
const extra={earn_money:['EARN_MONEY','รับงานแลกเบี้ยเลี้ยง','economy'],buy_personal:['BUY_ITEM','ซื้อโอสถด้วยเงินเก็บ','economy'],save_money:['SAVE_MONEY','พักและวางแผนเงินเก็บ','economy'],repay_favor:['REPAY_FAVOR','ตอบแทนความช่วยเหลือ','social'],build_trust:['BUILD_TRUST','ทำงานร่วมกันสร้างความเชื่อใจ','social'],verify_news:['VERIFY_INFORMATION','ตรวจสอบข่าวกับพยาน','knowledge'],share_news:['SHARE_INFORMATION','เล่าข่าวที่ตนรู้ให้สหาย','knowledge'],ask_promotion:['REQUEST_PROMOTION','เสนอผลงานขอเลื่อนตำแหน่ง','sect'],support_candidate:['SUPPORT_CANDIDATE','สนับสนุนผู้เหมาะสมในสำนัก','sect'],challenge_rival:['CHALLENGE','ท้าประลองคู่ปรับ','martial'],seek_weapon:['SEEK_BETTER_WEAPON','ขอซื้ออุปกรณ์ที่เหมาะกับตน','economy'],prepare_realm:['PREPARE_BREAKTHROUGH','เสริมฐานรากก่อนทะลวง','cultivation'],start_journey:['TRAVEL','ออกตามเบาะแสที่ตรวจสอบแล้ว','travel'],seek_ruins:['SEARCH_RUINS','สำรวจซากตามเบาะแส','travel'],return_journey:['RETURN_HOME','เดินทางกลับสำนัก','travel'],mourn_friend:['MOURN','ไว้อาลัยผู้ที่ผูกพัน','personal'],forgive:['FORGIVE','คลายความแค้นจากการคืนดี','personal']};
const oldActionId=N.actionId;N.actionId=key=>extra[key]?.[0]||oldActionId(key);
for(const [key,[id,name,category]]of Object.entries(extra)){N.ACTIVITIES[key]=name;N.registerAction(id,name,category,key,{risk:['CHALLENGE','TRAVEL','SEARCH_RUINS'].includes(id)?12:0,targets:['self','character','information','location'],costs:['BUY_ITEM','SEEK_BETTER_WEAPON','REPAY_FAVOR'].includes(id)?{wallet:'validated'}:{},hints:{goal:true,memory:true,need:true}})}
for(const [id,name,category]of [['SET_GOAL','ตั้งเป้าหมาย','personal'],['COMPLETE_GOAL','บรรลุเป้าหมาย','personal'],['FAIL_GOAL','พลาดเป้าหมาย','personal'],['ABANDON_GOAL','ละวางเป้าหมาย','personal'],['LEARN_RUMOR','ได้รับเบาะแส','knowledge'],['LOSE_DUEL','พ่ายประลอง','combat'],['WIN_DUEL','ชนะประลอง','combat'],['FIND_TREASURE','พบของจากการสำรวจ','travel'],['BECOME_JEALOUS','เกิดความริษยา','personal'],['REWARD_MEMBER','ได้รับรางวัล','sect'],['PROMOTE_MEMBER','เลื่อนตำแหน่ง','sect'],['PUNISH_MEMBER','ลงโทษสมาชิก','sect'],['DECLARE_WAR','ประกาศสงคราม','politics'],['SEEK_PEACE','แสวงหาสงบศึก','politics']])N.registerAction(id,name,category,'event',{actors:['world'],requirements:['actual_event'],duration:0});
W.stockPill=a=>{if(a.f)return null;const s=G.S,m=s.patch.management;return s.patch.items.find(i=>!i.owner&&!i.locked&&i.qty>m.itemReserve&&i.grade<=m.maxGrade&&P.items[i.def].type==='pill'&&N.pillNeeds(a.c).includes(P.items[i.def].effect)&&!N.pillError(i,a.c)&&N.itemValue(i)<=a.b.wallet)};
W.weapon=a=>{if(a.f)return null;const s=G.S,m=s.patch.management;return s.patch.items.filter(i=>!i.owner&&!i.locked&&i.qty>m.itemReserve&&i.grade<=m.maxGrade&&P.items[i.def].type==='weapon'&&!N.equipError(i,a.c)&&N.itemValue(i)<=a.b.wallet&&N.itemScore(a.c,i)>(N.owned(a.c,'weapon')?N.itemScore(a.c,N.owned(a.c,'weapon')):0)+1).sort((x,y)=>N.itemScore(a.c,y)-N.itemScore(a.c,x))[0]};
W.validateAction=(a,p)=>{if(!W.available(a)||W.health(a)<=0)return false;const t=p.target?W.person(p.target):null,id=p.id||N.actionId(p.key),s=G.S;if(!G.ACTIONS[id]?.supported)return false;if(p.target&&(!t||t.group!==a.group||!W.available(t)))return false;switch(p.key){case'earn_money':return s.patch.management.enabled&&(a.f?a.f.wealth>30:N.reserveAllows({silver:2}));case'buy_personal':return !a.f&&s.patch.management.autoPills&&!!W.stockPill(a);case'seek_weapon':return !a.f&&s.patch.management.autoEquip&&!!W.weapon(a);case'repay_favor':return !!t&&a.b.wallet>=2&&W.rel(a,t.id).debt>0;case'build_trust':return !!t;case'verify_news':return a.b.knowledge.some(k=>!k.verified&&W.state().events.some(e=>e.id===k.event));case'share_news':return !!t&&a.b.knowledge.some(k=>!t.b.knowledge.some(x=>x.event===k.event));case'ask_promotion':return !a.f&&a.c.rank<3&&!a.c.mx.managementLock&&s.patch.management.autoPromote&&a.c.loy>=55&&a.c.realm>=a.c.rank+1&&(a.c.merit||0)>=8;case'support_candidate':return !!t&&!a.f&&t.c.rank>=2;case'challenge_rival':return !!t&&W.health(a)>80&&W.health(t)>80&&W.fatigue(a)<55&&W.fatigue(t)<55&&Math.abs(W.realm(a)-W.realm(t))<=1&&W.rel(a,t.id).rivalry>20;case'start_journey':return !a.f&&s.patch.management.autoMissions&&!a.c.jobFix&&!a.c.mx.managementLock&&!Object.values(s.patch.offices).includes(a.id)&&a.id!==s.sect.leader&&W.health(a)>85&&W.fatigue(a)<45&&s.res.food>s.order.length*(s.patch.management.foodDays+5)&&a.b.knowledge.some(k=>k.type==='LEARN_RUMOR'&&k.verified&&G.LOCS[k.location]&&s.discovered[k.location]&&G.LOCS[k.location].danger<=Math.max(1,W.realm(a)));case'mourn_friend':return a.b.memories.some(m=>m.type==='MOURN'&&s.day-m.day<30);case'forgive':return !!t&&W.rel(a,t.id).hatred>0&&W.rel(a,t.id).trust>25;case'prepare_realm':return W.realm(a)<G.PATHS[a.f?a.f.path:a.c.path].realms.length;default:return true}};
W.candidates=a=>{const s=G.S,n=a.b.needs,out=[],peers=W.people().filter(t=>t!==a&&t.group===a.group&&W.available(t));const add=(key,score,why,target)=>out.push({key,id:extra[key]?.[0],score,why,target:target?.id||null,data:null});
if(n.wealth>35)add('earn_money',20+n.wealth*.35,'เงินเก็บต่ำ รับงานที่สำนักจ่ายไหว');if(W.stockPill(a))add('buy_personal',55+n.healing*.2,'ใช้เงินตนเองซื้อโอสถในคลังที่นโยบายอนุญาต');if(W.weapon(a))add('seek_weapon',50+W.attr(a,'amb')*.15,'อาวุธในคลังดีกว่าชิ้นเดิมและมีเงินพอ');if(a.b.wallet>=10)add('save_money',12+W.attr(a,'cau')*.2,'รักษาทุนไว้ตามนิสัยและแผนซื้อของ');
const friend=peers.slice().sort((x,y)=>W.rel(a,y.id).trust-W.rel(a,x.id).trust)[0],rival=peers.filter(t=>W.rel(a,t.id).rivalry>20).sort((x,y)=>W.rel(a,y.id).rivalry-W.rel(a,x.id).rivalry)[0],creditor=peers.find(t=>W.rel(a,t.id).debt>0);if(creditor)add('repay_favor',25+W.rel(a,creditor.id).gratitude*.2,'จำบุญคุณและยังติดความช่วยเหลือ',creditor);if(friend){add('build_trust',20+n.social*.2,'เลือกคนที่ไว้ใจเพื่อทำงานร่วมกัน',friend);if(a.b.knowledge.length)add('share_news',15+W.attr(a,'soc')*.15,'แลกข่าวที่ตนทราบ',friend);if(W.rel(a,friend.id).hatred>0&&W.rel(a,friend.id).trust>25)add('forgive',35,'ความเชื่อใจเริ่มกลับมาหลังช่วยเหลือกัน',friend)}
if(a.b.knowledge.some(k=>!k.verified))add('verify_news',32+W.attr(a,'cau')*.3,'ตรวจต้นข่าวก่อนเปลี่ยนแผนหรือออกเดินทาง');if(!a.f&&a.c.rank<3)add('ask_promotion',25+W.attr(a,'amb')*.3,'นำผลงานจริงเสนอผู้บริหาร');const elder=peers.find(t=>!t.f&&t.c.rank>=2&&t.id!==s.sect.leader&&W.rel(a,t.id).respect>20);if(elder)add('support_candidate',20+W.attr(a,'amb')*.12,'สนับสนุนคนที่เคารพให้มีเสียงในสำนัก',elder);if(rival)add('challenge_rival',25+W.attr(a,'cou')*.25+W.rel(a,rival.id).rivalry*.25,'เตรียมตัวจากความทรงจำการประลอง',rival);
add('prepare_realm',20+(W.progress(a)>=W.need(a)?35:0),'ฐานรากต้องรองรับขอบเขตถัดไป');if(!a.f)add('start_journey',30+W.attr(a,'cou')*.2,'ติดตามเบาะแสที่ยืนยันแล้วโดยจ่ายเสบียงจริง');if(a.b.memories.some(m=>m.type==='MOURN'&&s.day-m.day<30))add('mourn_friend',40,'การจากไปของคนใกล้ชิดยังติดอยู่ในใจ');return out.filter(p=>W.validateAction(a,p)).map(p=>W.score(a,p))};
const candidates=N.planCandidates;N.planCandidates=(c,local)=>{const a={id:c.id,name:c.name,c,b:c.mx.brain,f:null,group:'player'};W.needs(a);const old=candidates(c,local).map(p=>W.score(a,p));const all=[...old,...W.candidates(a)].filter(p=>W.validateAction(a,p));W.state().metrics.candidates+=all.length;all.sort((x,y)=>y.score-x.score||x.key.localeCompare(y.key));if(W.state().debug){W._candidateDebug??={};W._candidateDebug[c.id]=all.slice(0,8).map(p=>({action:p.id,score:+p.score.toFixed(2),reasons:p.reasons,why:p.why}));}return all};
// Store candidates only at execution, rather than every speculative agenda construction.
W.trace=(a,p,success,before=null)=>{const q=W.state();q.metrics.decisions++;q.metrics[success?'success':'rejected']++;const row={day:G.S.day,action:p.id||N.actionId(p.key),target:p.target||null,score:+p.score.toFixed(2),reasons:p.reasons||{},why:p.why,goal:a.b.focus,success,delta:before?{wallet:+(a.b.wallet-before.wallet).toFixed(4)}:{}};if(q.debug){row.candidates=W._candidateDebug?.[a.id]||[];row.memories=a.b.memories.filter(m=>m.target===p.target&&m.importance>50).slice(0,4).map(m=>m.event)}if(!a.f&&success){const ev=a.c.mx.life.history[0];if(ev?.day===G.S.day)Object.assign(row.delta,ev.changes)}a.b.trace.unshift(row);a.b.trace=a.b.trace.slice(0,q.debug?24:8)};
W.record=(a,id,text,target=null,changes={})=>{for(const g of a.b.goals){if(g.steps[g.cursor]===id){g.cursor++;g.attempts++;if(g.cursor>=g.steps.length)g.cursor=0}}if(a.b.plan&&a.b.goals[0])a.b.plan.steps=a.b.goals[0].steps.slice(a.b.goals[0].cursor);a.b.lastAction=G.S.day;a.b.counts[id]=(a.b.counts[id]||0)+1;a.b.month[id]=(a.b.month[id]||0)+1;const e=W.emit(id,a.id,target,text,{importance:['CHALLENGE','VERIFY_INFORMATION','TRAVEL','FIND_TREASURE','REQUEST_PROMOTION'].includes(id)?60:25,effects:changes});return e};
const event=N.lifeEvent;N.lifeEvent=(c,key,why,detail,target,changes={})=>{const e=event(c,key,why,detail,target,changes);if(c.mx.brain){const a=W.person(c.id);if(a)W.record(a,N.actionId(key),c.name+' '+detail,target,changes)}return e};
const perform=N.performExtra;N.performExtra=(c,p)=>{if(!extra[p.key])return perform(c,p);const a=W.person(c.id),before={wallet:a.b.wallet};if(!W.validateAction(a,p)){W.trace(a,p,false,before);return false}const text=W.execute(a,p);W.trace(a,p,!!text,before);if(!text)return false;N.lifeEvent(c,p.key,p.why,text,p.target,{wallet:+(a.b.wallet-before.wallet).toFixed(3)});return true};
W.execute=(a,p)=>{const s=G.S,b=a.b,t=p.target&&W.person(p.target);switch(p.key){case'earn_money':{const pay=a.f?1:2;if(a.f){if(a.f.wealth<pay+30)return null;a.f.wealth-=pay;a.f.stock+=.12;a.c.mx.fatigue=C(a.c.mx.fatigue+1,0,100)}else{if(!N.reserveAllows({silver:pay}))return null;G.add('silver',-pay,'ค่าจ้างงานเสริม');G.add(a.c.job==='mine'?'ore':a.c.job==='herb'?'herb':'food',.15,'แรงงานเสริม');a.c.fat=C(a.c.fat+1,0,100);a.c.merit=(a.c.merit||0)+.12}b.wallet+=pay;return 'รับงานเสริม ใช้ทุนสำนัก '+pay+' เพิ่มของจริง 0.15 และเก็บค่าจ้าง'}
case'buy_personal':{const i=W.stockPill(a);if(!i)return null;const cost=N.itemValue(i),name=P.items[i.def].name;const err=N.usePill(i.id,a.id);if(err)return null;b.wallet-=cost;G.add('silver',cost,'ศิษย์ซื้อโอสถจากคลัง');return 'ใช้เงินเก็บ '+cost+' ซื้อและใช้ '+name}
case'seek_weapon':{const i=W.weapon(a);if(!i)return null;const cost=N.itemValue(i),name=P.items[i.def].name;if(N.equip(i.id,a.id))return null;b.wallet-=cost;G.add('silver',cost,'ศิษย์ซื้ออุปกรณ์จากคลัง');return 'ใช้เงินเก็บ '+cost+' ซื้อ '+name+' แล้วสวมใช้งาน'}
case'save_money':if(a.f)a.c.mx.stress=C(a.c.mx.stress-.8,0,100);else a.c.stress=C(a.c.stress-.8,0,100);return 'จัดแผนเงินเก็บ '+G.f1(b.wallet)+' เหรียญ ลดความกังวลโดยไม่สร้างรายได้';
case'repay_favor':b.wallet-=2;t.b.wallet+=2;W.relate(a,t.id,{debt:-2,gratitude:1});W.relate(t,a.id,{trust:2,affection:1});W.state().metrics.transfers++;return 'มอบเงินเก็บ 2 เหรียญตอบแทน '+t.name;
case'build_trust':W.relate(a,t.id,{trust:1,respect:.4});W.relate(t,a.id,{trust:1,respect:.4});if(a.f)a.c.mx.stress=C(a.c.mx.stress-.5,0,100);else a.c.sat=C(a.c.sat+.2,0,100);return 'ทำงานร่วมกับ '+t.name+' ความเชื่อใจของทั้งสองเพิ่มขึ้น';
case'share_news':{const k=b.knowledge.find(k=>!t.b.knowledge.some(x=>x.event===k.event)),e=k&&W.state().events.find(e=>e.id===k.event);if(!e)return null;W.learn(t,e,'conversation',k.confidence*.85,k.claim);W.relate(t,a.id,{trust:.3});return 'บอก '+t.name+' ว่า '+k.claim}
case'verify_news':{const k=b.knowledge.find(k=>!k.verified&&W.state().events.some(e=>e.id===k.event)),e=k&&W.state().events.find(e=>e.id===k.event);if(!e)return null;const witness=W.people().find(t=>t.group===a.group&&t.b.knowledge.some(x=>x.event===k.event&&x.verified));if(!witness&&e.group!==a.group)return null;k.verified=true;k.confidence=1;k.claim=e.text;k.source='verified';return 'ตรวจต้นข่าวกับ '+(witness?.name||'รายงานสำนัก')+' ยืนยันว่า '+e.text}
case'ask_promotion':{const r=G.promote(a.c,1);if(!r.ok)return null;a.c.merit=Math.max(0,(a.c.merit||0)-8);return 'เสนอผลงานและได้รับตำแหน่ง '+G.RANKS[a.c.rank]}
case'support_candidate':b.cohort=t.id;W.relate(a,t.id,{loyalty:1,respect:.5});W.relate(t,a.id,{trust:.5,debt:.2});return 'สนับสนุน '+t.name+' หลังพิจารณาความเคารพและงานที่ผ่านมา';
case'challenge_rival':{const power=x=>a.f?G.tierPow(W.realm(x))*(.6+x.c.mx.foundation/100):G.fighter(x.c).atk*G.fighter(x.c).hp;const pa=power(a),pt=power(t),win=pa*(.95+(N.hash(a.id+'|'+s.day)%11)/100)>pt,loser=win?t:a,winner=win?a:t;if(a.f){a.c.mx.fatigue=C(a.c.mx.fatigue+3,0,100);t.c.mx.fatigue=C(t.c.mx.fatigue+3,0,100);loser.c.mx.health=C(loser.c.mx.health-3,0,100)}else{a.c.fat=C(a.c.fat+3,0,100);t.c.fat=C(t.c.fat+3,0,100);loser.c.hp=C(loser.c.hp-3,0,100);a.c.merit=(a.c.merit||0)+(win?.5:.1)}W.relate(loser,winner.id,{rivalry:3,hatred:W.attr(loser,'amb')>65?2:0,respect:1});W.emit('LOSE_DUEL',loser.id,winner.id,loser.name+' แพ้ประลองให้ '+winner.name,{importance:75,emotion:-12,public:true});W.emit('WIN_DUEL',winner.id,loser.id,winner.name+' ชนะประลอง '+loser.name,{importance:60,emotion:8});return 'ท้าประลอง '+t.name+' ผล: '+(win?'ชนะ':'แพ้')+' จากขอบเขต สภาพร่างกาย และฝีมือจริง'}
case'prepare_realm':if(a.f){a.c.mx.foundation=C(a.c.mx.foundation+.18,0,100);a.c.mx.fatigue=C(a.c.mx.fatigue+.6,0,100)}else{a.c.found=C(a.c.found+.18,0,100);a.c.fat=C(a.c.fat+.6,0,100)}return 'ใช้เวลาปรับฐานรากก่อนทะลวง ฐานรากเพิ่ม 0.18';
case'start_journey':{const k=b.knowledge.find(k=>k.type==='LEARN_RUMOR'&&k.verified&&G.LOCS[k.location]&&s.discovered[k.location]&&G.LOCS[k.location].danger<=Math.max(1,W.realm(a))),loc=k?.location;if(!loc)return null;const days=N.travelDays(loc,[a.c]),food=2*days+3;if(s.res.food-food<s.order.length*s.patch.management.foodDays)return null;G.add('food',-food,'เสบียงติดตามเบาะแส');b.travel={location:loc,phase:'go',remaining:days,travelDays:days,started:s.day,source:k.event,resumeJob:a.c.job,resumeFix:a.c.jobFix};a.c.state='worldTravel';a.c.job='rest';a.c.jobFix=1;return 'ออกตามเบาะแส '+G.LOCS[loc].n+' ใช้เสบียง '+food+' เดินทาง '+days+' วัน'}
case'mourn_friend':if(a.f)a.c.mx.stress=C(a.c.mx.stress-1,0,100);else{a.c.stress=C(a.c.stress-1,0,100);a.c.mind=C(a.c.mind+.2,0,100)}return 'หยุดไว้อาลัยและค่อย ๆ ประคองใจหลังการสูญเสีย';
case'forgive':W.relate(a,t.id,{hatred:-2,rivalry:-1,trust:.5});return 'ความช่วยเหลือที่ผ่านมาเริ่มทำให้ยอมคลายแค้นต่อ '+t.name;
default:return null}};
// Legacy actions now choose the highest contextual utility; seeded hashes only break ties.
N.planAgenda=(c,local)=>{const agenda=[],keys=[];for(const slot of N.SLOTS){N._planningSlot=slot;N._dayKeys=keys;const p=N.planCandidates(c,local)[0];if(p){agenda.push({...p,slot,since:G.S.day,until:G.S.day});keys.push(p.key)}}return agenda};
W.extraKey=key=>!!extra[key];
const personal=N.personalGoal;N.personalGoal=c=>c.mx.brain?.focus?W.GOALS[c.mx.brain.focus].name:personal(c);
})(window.G);
