/* Thai summaries expose outcomes; diagnostics are opt-in and never run a simulation. */
(function(G){'use strict';const U=G.UI,N=G.N,W=G.WORLD,E=U.esc,A=U.A;
const dim=t=>'<div class="dim">'+t+'</div>',card=(t,h)=>'<section class="card"><h3>'+E(t)+'</h3>'+h+'</section>',btn=(label,action,data={})=>'<button type="button" class="sm ap-action" data-a="'+action+'" '+Object.entries(data).map(([k,v])=>'data-'+k+'="'+E(v)+'"').join(' ')+'>'+E(label)+'</button>',row=h=>'<div class="item">'+h+'</div>',select=(id,rows,current)=>'<select id="'+id+'">'+rows.map(([v,n])=>'<option value="'+E(v)+'"'+(v===current?' selected':'')+'>'+E(n)+'</option>').join('')+'</select>';
W.personSheet=id=>{const a=W.person(id);if(!a)return card('ไม่พบบุคคล',dim('บุคคลนี้จากไปแล้ว'));const b=a.b;
return card('แผนชีวิตของ '+a.name,dim('เงินเก็บ '+G.f1(b.wallet)+' เหรียญ • '+(b.tier===1?'ติดตามละเอียด':b.tier===2?'ติดตามตามสถานการณ์':'ติดตามเบื้องหลัง'))+b.goals.map(g=>row('<b>'+E(W.GOALS[g.kind].name)+'</b>'+dim(({short:'ระยะสั้น',medium:'ระยะกลาง',long:'ระยะยาว'}[g.horizon])+' • ความสำคัญ '+Math.round(g.priority)+' • คืบหน้า '+Math.round(g.progress*100)+'%')+dim('แผน: '+E((g.steps.length?g.steps:W.goalPlan(a,g)).map(id=>G.ACTIONS[id]?.name||id).join(' → '))))).join(''))+
card('ความทรงจำที่ยังมีผล',b.memories.slice(0,12).map(m=>row('วัน '+m.day+' • '+E(m.text)+dim('น้ำหนัก '+Math.round(m.importance)+' • '+(m.decay===0?'จดจำระยะยาว':'ค่อย ๆ จางตามเวลา')))).join('')||dim('ยังไม่มีเหตุการณ์สำคัญ'))+
card('ข่าวที่บุคคลนี้ทราบ',b.knowledge.slice(0,12).map(k=>row(E(k.claim)+dim('รับข่าววัน '+k.heard+' • '+(k.verified?'ยืนยันแล้ว':'ยังไม่ยืนยัน')+' • ความมั่นใจ '+Math.round(k.confidence*100)+'%'))).join('')||dim('ยังไม่มีข่าว'))+
card('ความสัมพันธ์หลายด้าน',Object.entries(b.relations).sort((x,y)=>Math.abs(y[1].trust)+y[1].rivalry-Math.abs(x[1].trust)-x[1].rivalry).slice(0,10).map(([id,r])=>row('<b>'+E(W.person(id)?.name||'ผู้จากไป')+'</b>'+dim('ไว้ใจ '+G.f1(r.trust)+' • เคารพ '+G.f1(r.respect)+' • รักใคร่ '+G.f1(r.affection)+' • กลัว '+G.f1(r.fear))+dim('คู่ปรับ '+G.f1(r.rivalry)+' • ริษยา '+G.f1(r.jealousy)+' • บุญคุณ '+G.f1(r.gratitude)+' • ติดหนี้ช่วยเหลือ '+G.f1(r.debt)+' • ภักดี '+G.f1(r.loyalty)+' • แค้น '+G.f1(r.hatred)))).join('')||dim('ยังไม่มีสายสัมพันธ์ที่ติดตาม'))+
(b.months.length?card('พงศาวดารส่วนตัว',b.months.slice(0,3).map(m=>row('วัน '+m.day+' • '+E(m.text))).join('')):'')+
(W.state().debug?card('ตรวจการตัดสินใจ',b.trace.slice(0,6).map(t=>row('วัน '+t.day+' • '+E(G.ACTIONS[t.action]?.name)+' • คะแนน '+t.score+' • '+(t.success?'สำเร็จ':'เงื่อนไขไม่ผ่าน')+dim(E(t.why))+dim('เหตุผลคะแนน: '+E(JSON.stringify(t.reasons)))+dim('ผลจริง: '+E(JSON.stringify(t.delta)))+(t.candidates?.length?'<details><summary>ทางเลือกที่ประเมิน</summary>'+t.candidates.map(c=>dim(E(G.ACTIONS[c.action]?.name)+' '+c.score+' • '+E(c.why))).join('')+'</details>':''))).join('')):'');};
U.M.worldPerson=id=>W.personSheet(id);
U.M.worldSimulation=()=>{const q=W.state(),e=q.economy,latest=q.reports[0],people=W.people(),visible=people.filter(a=>!a.f||q.debug||a.f.pact||a.f.detail||a.f.stance==='ally');
return card('โลกที่ดำเนินต่อไป',dim('แต่ละวันจำลองหกช่วง พร้อมเป้าหมาย ข่าวสาร และผลสะสมของการตัดสินใจ')+ '<label>ความละเอียด'+select('world-quality',[['DEEP','ลึก — ค่าเริ่มต้น'],['NORMAL','ปกติ'],['LOW','เบา']],q.quality)+'</label>'+btn('ใช้ความละเอียดที่เลือก','world-quality')+btn(q.debug?'ปิดการตรวจการตัดสินใจ':'เปิดการตรวจการตัดสินใจ','world-debug')+dim('การประเมิน '+G.f0(q.metrics.candidates)+' ทางเลือก • กิจกรรมสำเร็จ '+G.f0(q.metrics.success)+' • บรรลุเป้าหมาย '+q.metrics.goalsCompleted))+
card('เส้นทางค้าและทรัพยากร',dim('เส้นทางเดินทางได้ '+Math.round(e.routeSafety*100)+'% • ราคาโอสถ '+e.medicinePrice.toFixed(2)+' เท่า')+dim('สมุนไพรตลาด '+G.f1(e.herbSupply)+' • แร่ตลาด '+G.f1(e.oreSupply))+dim('สงคราม ภัยถนน สภาพอากาศ และพื้นที่ที่ฝ่ายศัตรูครอง มีผลต่อการส่งของและราคา'))+
card('แผนชีวิตและเหตุผลของบุคคล',visible.map(a=>row('<b>'+E(a.name)+'</b>'+dim(E(a.f?a.f.n:G.S.sect.name)+' • '+E(a.b.focus?W.GOALS[a.b.focus].name:'กำลังประเมินเป้าหมาย'))+btn('เป้าหมาย / ความทรงจำ / ข่าวที่รู้','world-person',{id:a.id}))).join(''))+
card('พงศาวดารเดือนล่าสุด',latest?dim('วัน '+latest.day+' • '+latest.actions+' กิจกรรมของคนที่ติดตาม')+latest.people.filter(r=>visible.some(a=>a.id===r.id)).map(r=>row(E(r.text))).join('')+latest.events.map(e=>dim('วัน '+e.day+' • '+E(e.text))).join(''):dim('ครบ 30 วันจะสรุปจากกิจกรรมและผลที่เกิดขึ้นจริง'))+
card('สำนักภายนอก',G.S.factions.filter(f=>!f.dead).map(f=>{const o=f.mx.organization;return row('<b>'+E(f.n)+'</b>'+dim('แนวทางล่าสุด: '+E(G.ACTIONS[o.plan]?.name||'รักษาความอยู่รอด')+' • สภาพคลังและการลงทุนมีผลต่อการฝึก')+(q.debug||f.pact||f.detail?o.history.slice(0,3).map(h=>dim('วัน '+h.day+' • '+E(h.text)+' • '+E(h.why))).join(''):dim('ยังไม่มีสายรายงานกิจการภายใน')))}).join(''))+
(q.debug?card('คำการกระทำที่ระบบรองรับ',dim('กิจกรรมต้องผ่านเงื่อนไขจริง ผลเหตุการณ์และงานประจำแสดงแยกในทะเบียนกิจกรรมทั้งหมด')+Object.entries(N.actionCategories).map(([cat,name])=>'<details><summary>'+E(name)+'</summary>'+Object.values(G.ACTIONS).filter(a=>a.category===cat&&a.supported).map(a=>dim(E(a.id)+' • '+E(a.name))).join('')+'</details>').join('')):'');};
A['world-open']=()=>U.open('worldSimulation');A['world-person']=d=>U.open('worldPerson',d.id);
A['world-debug']=()=>{W.state().debug=!W.state().debug;W._candidateDebug={};G.save('auto');U.open('worldSimulation')};
A['world-quality']=()=>{const v=document.getElementById('world-quality').value;if(W.QUALITY[v]){W.state().quality=v;const cfg=W.config();for(const a of W.people()){a.b.memories=a.b.memories.slice(0,cfg.memories);a.b.knowledge=a.b.knowledge.slice(0,cfg.knowledge);a.b.nextDecision=Math.min(a.b.nextDecision,G.S.day+1)}W.state().events=W.state().events.slice(-cfg.events);G.save('auto');U.open('worldSimulation')}};
const home=U.V.home;U.V.home=()=>home()+card('พงศาวดารและแผนชีวิต',dim('ดูว่าแต่ละคนกำลังมุ่งอะไร รู้ข่าวอะไร และเหตุใดจึงเลือกทำเช่นนั้น')+btn('เปิดโลกจำลอง','world-open'));
const char=U.M.char;U.M.char=id=>char(id)+(G.S.chars[id]?card('เป้าหมายและความทรงจำ',btn('ดูแผนชีวิตของบุคคลนี้','world-person',{id})):'' );
for(const key of ['lives','steward']){const old=N.views[key];N.views[key]=()=>card('โลกจำลอง',btn('พงศาวดาร / เป้าหมาย / ตรวจการตัดสินใจ','world-open'))+old()}
const simulation=U.M.worldSimulation;
U.M.worldSimulation=()=>simulation()+card('แหล่งทรัพยากรและการควบคุม',dim('ของในแหล่งมีจำกัดและค่อย ๆ ฟื้น การยึดต้องใช้ทุน เสบียง และกำลังที่พร้อมรบ')+Object.entries(W.state().sites).filter(([id])=>G.S.discovered[id]&&G.LOCS[id].k!=='trade').map(([id,x])=>row('<b>'+E(G.LOCS[id].n)+'</b>'+dim('ผู้ควบคุม: '+E(x.owner==='player'?G.S.sect.name:G.S.factions.find(f=>f.id===x.owner&&!f.dead)?.n||'ไม่มีผู้ควบคุม'))+(x.owner==='player'?dim('ส่งทรัพยากรตามปริมาณที่เหลือทุก 7 วัน'):btn('จัดกำลังยึดพื้นที่','world-capture',{id})))).join(''));
A['world-capture']=d=>{const squad=G.home().filter(c=>W.available(W.person(c.id))&&c.hp>=70&&c.fat<=65).sort((a,b)=>b.realm-a.realm).slice(0,3);
 if(!squad.length)return U.res({ok:false,msg:'ไม่มีสมาชิกพร้อมรบ'});
 const cost=squad.length*3+5;if(!confirm('ส่ง '+squad.map(c=>c.name).join(', ')+' ยึด '+G.LOCS[d.id].n+'? ใช้ทุน 50 และเสบียง '+cost+' การรบอาจบาดเจ็บหรือเสียชีวิต'))return;
 const r=W.captureSite(d.id,squad.map(c=>c.id));G.save('auto');U.res(r);
};
})(window.G);
