const assert=require('node:assert/strict'),G=require('./harness'),N=G.N,P=G.PATCH,fs=require('node:fs'),path=require('node:path');
let pass=0;const test=(name,fn)=>{try{fn();pass++;console.log('PASS',name)}catch(e){console.error('FAIL',name,e.stack);process.exitCode=1}};
function fresh(seed=7){G.newGame(seed);const s=G.S;s.patch.management.enabled=false;s.patch.management.autoMentors=false;s.patch.management.autoStudy=false;s.sect.policies.autoAssign=0;s.sect.policies.autoBT='off';for(const c of G.alive()){c.master=null;Object.assign(c.mx.apprentice,{masterId:null,guidanceUntil:0,sessions:0});c.mx.study=null;c.mx.busyUntil=0;c.hp=100;c.fat=0;c.stress=0;c.jobFix=1}for(const k of Object.keys(s.res))s.res[k]=10000;const[t,c]=G.home();t.rank=3;t.realm=4;t.path='qi';t.manual='qi_cloud';t.at.int=95;t.at.dis=90;t.traits=['sm_mentorGift'];t.job='teach';c.rank=0;c.realm=1;c.path='qi';c.manual='qi_cloud';c.at.int=65;c.at.dis=90;c.apt.qi=95;c.found=100;c.job='cultivate';c.traits=['sm_diligent'];t.rel[c.id]=30;c.rel[t.id]=30;return {s,t,c}}
const walk=n=>{for(let i=0;i<n&&!G.S.over;i++){G.stepDay();for(const p of G.S.pending.slice())G.decide(p.id,p.def)}};
const valid=()=>{const r=G.validate(G.serialize());assert(r.ok,r.msg)};
const checksum=o=>{let h=5381;const b=JSON.stringify(o.S);for(let i=0;i<b.length;i++)h=((h<<5)+h+b.charCodeAt(i))|0;o.sum=h;return JSON.stringify(o)};
function unknown(t,c){const a=Object.values(P.arts).find(a=>a.paths.includes('qi')&&!a.manuals?.length&&a.tier===1&&!G.S.patch.knownArts.includes(a.id));assert(a);t.mx.arts.push(a.id);t.mx.mastery[a.id]=80;t.mx.active=[];return a}
test('teacher invitation requires both decisions and stores both reasons',()=>{const {t,c}=fresh();assert(N.proposeMentor(t.id,c.id,'teacher').ok);assert.equal(c.master,t.id);assert(c.mx.apprentice.teacherReason.includes('มรรคา'));assert(c.mx.apprentice.studentReason.includes('เรียน'));assert.equal(G.S.patch.mentorship.history[0].direction,'teacher');valid()});
test('student request is accepted independently and failed request cannot replace a master',()=>{const {t,c}=fresh();assert(N.proposeMentor(t.id,c.id,'student').ok);const other=G.home()[2];assert(!N.proposeMentor(other.id,c.id,'teacher').ok);assert.equal(c.master,t.id)});
test('teacher can refuse unsuitable temperament and talent',()=>{const {t,c}=fresh();c.apt.qi=0;c.at.dis=0;c.traits=['sm_lazy'];c.rel[t.id]=-60;t.rel[c.id]=-60;const r=N.proposeMentor(t.id,c.id,'student');assert(!r.ok);assert.equal(c.master,null);assert.equal(G.S.patch.mentorship.history[0].result,'declined');valid()});
test('student can refuse even when the teacher wants to accept',()=>{const {t,c}=fresh();t.realm=c.realm=1;t.at.int=95;c.at.int=60;c.path='body';c.manual='body_iron';c.traits=['sm_proud'];c.apt.qi=100;t.rel[c.id]=c.rel[t.id]=0;const a=N.mentorAssessment(t,c);assert(a.teacherAccept,JSON.stringify(a));assert(!a.studentAccept);assert(!N.proposeMentor(t.id,c.id,'teacher').ok);assert.equal(c.master,null)});
test('mentor capacity, self relation and cyclic lineage are rejected',()=>{const {t,c}=fresh();assert(!N.proposeMentor(c.id,c.id).ok);for(const x of G.home().filter(x=>x!==t&&x!==c).slice(0,N.mentorCapacity(t)))x.master=t.id;assert(!N.proposeMentor(t.id,c.id).ok);for(const x of G.home())x.master=null;t.master=c.id;assert(N.mentorCycle(t,c));assert(!N.proposeMentor(t.id,c.id).ok)});
test('master increases actual cultivation and bonus disappears when absent',()=>{const {s,t,c}=fresh();const baseline=N.training(c);assert(N.proposeMentor(t.id,c.id).ok);assert(N.training(c)>baseline);const boost=N.mentorBenefit(c).training;assert(boost>0&&boost<=.4);assert(N.mentorBenefit(c).breakthrough>0);t.state='exp';assert.equal(N.training(c),baseline);t.state='home';t.mx.study={id:'x'};assert.equal(N.training(c),baseline);t.mx.study=null;const snap=G.serialize();walk(1);const withMaster=c.prog;assert(G.loadText(snap).ok);const cc=G.S.chars[c.id];cc.master=null;walk(1);assert(withMaster>cc.prog,'actual daily cultivation gain');valid()});
test('personal lessons spend resources, complete, and never unlock public knowledge',()=>{const {s,t,c}=fresh();const a=unknown(t,c);assert(N.proposeMentor(t.id,c.id).ok);const outsider=G.home()[2];outsider.path='qi';outsider.realm=4;outsider.manual='qi_cloud';assert(!N.allowedArt(outsider,a.id));assert(N.allowedArt(c,a.id));const before={...s.res};assert.equal(N.learn(c.id,a.id,t.id),'');assert(Object.keys(before).some(k=>s.res[k]<before[k]));t.job='craft';for(let i=0;i<100&&c.mx.study;i++){s.day++;N.dailyArts()}assert(c.mx.arts.includes(a.id));assert(c.mx.apprentice.learned.includes(a.id));assert(!s.patch.knownArts.includes(a.id));assert(!N.allowedArt(outsider,a.id));valid()});
test('low teacher mastery and absent teacher cannot provide personal instruction',()=>{const {t,c}=fresh();const a=unknown(t,c);assert(N.proposeMentor(t.id,c.id).ok);t.mx.mastery[a.id]=59;assert(!N.allowedArt(c,a.id));t.mx.mastery[a.id]=80;assert.equal(N.learn(c.id,a.id,t.id),'');const before=c.mx.study.remaining;t.state='exp';N.dailyArts();assert.equal(c.mx.study.remaining,before);t.state='home';G.die(t,'ทดสอบ');assert(!c.mx.study);assert(!G.S.patch.knownArts.includes(a.id));valid()});
test('paired mentor session gives bounded guidance and occupies both slots',()=>{const {s,t,c}=fresh();assert(N.proposeMentor(t.id,c.id).ok);const before=c.found;c.found=60;N._planningSlot='dusk';assert(N.performExtra(c,{key:'master_session',target:t.id,why:'ทดสอบ'}));assert(c.found>60&&c.found<61);assert.equal(c.mx.apprentice.sessions,1);assert(c.mx.apprentice.guidanceUntil>s.day);assert.equal(c.mx.life.history[0].slot,'dusk');assert.equal(t.mx.life.history[0].slot,'dusk');assert(!N.performExtra(c,{key:'master_session',target:t.id,why:'ซ้ำ'}));valid()});
test('mentor care consumes only permitted medicine and does not invent healing stock',()=>{const {s,t,c}=fresh();assert(N.proposeMentor(t.id,c.id).ok);s.patch.management.enabled=true;s.patch.management.autoEquip=false;s.patch.management.autoPills=false;c.hp=40;c.fat=70;N.addItem('root_pill',5);const qty=N.itemCount('root_pill');N._planningSlot='dusk';assert(N.performExtra(c,{key:'master_care',target:t.id,why:'เจ็บ'}));assert.equal(N.itemCount('root_pill'),qty);assert.equal(c.hp,40);assert(c.fat<70);s.day+=7;s.patch.management.autoPills=true;s.patch.management.budget=1000;assert(N.performExtra(c,{key:'master_care',target:t.id,why:'เจ็บ'}));assert(c.hp>40);assert(N.itemCount('root_pill')<qty);assert(s.patch.allocationDaySpent>0);valid()});
test('Grok item system obeys disabled policies, reserves, grade and budget',()=>{const {s}=fresh();const m=s.patch.management;m.enabled=true;m.leaderUse=true;m.autoEquip=false;m.autoPills=false;m.autoRefine=false;m.autoStudy=false;m.autoSell=false;m.autoCommunity=false;m.budget=0;m.maxGrade=0;m.itemReserve=999;N.addItem('iron_sword',3);const count=N.itemCount('iron_sword'),hp=G.home()[3].hp=40;N.addItem('root_pill',5);N.processItems();assert(!G.home().some(c=>N.owned(c,'weapon')));assert.equal(N.itemCount('iron_sword'),count);assert.equal(G.home()[3].hp,hp);valid()});
test('production help cannot overflow a nearly finished order',()=>{const {s,c}=fresh();const def=Object.keys(P.items).find(id=>P.items[id].craftable&&s.patch.knownRecipes.includes(id)&&!N.recipeError(id));assert(def);assert.equal(N.queue(def),'');const q=s.patch.orders[0];q.done=q.work-.01;N._planningSlot='dusk';assert(N.performExtra(c,{key:'help_other',why:'งานค้าง',target:null}));assert(!s.patch.orders.includes(q)||q.done<=q.work);valid()});
test('damaged Grok schema 5 overflow migrates without extra stock and detects bad checksum',()=>{const {s}=fresh();const def=Object.keys(P.items).find(id=>P.items[id].craftable&&s.patch.knownRecipes.includes(id)&&!N.recipeError(id));N.queue(def);s.patch.orders[0].done=s.patch.orders[0].work+.1;const o=JSON.parse(G.serialize());o.S.schema=o.schema=5;delete o.S.patch.mentorship;for(const c of Object.values(o.S.chars))delete c.mx.apprentice;const text=checksum(o),silver=o.S.res.silver;const r=G.loadText(text);assert(r.ok,r.msg);assert.equal(G.S.schema,G.SCHEMA);assert.equal(G.S.res.silver,silver);assert.equal(G.S.patch.orders[0].done,G.S.patch.orders[0].work);o.S.res.silver++;assert(!G.loadText(JSON.stringify(o)).ok);valid()});
test('malformed new fields and lineage cycles are rejected atomically',()=>{fresh();const before=G.serialize();const o=JSON.parse(before);o.S.chars[o.S.order[0]].mx.apprentice.sessions='wrong';assert(!G.loadText(checksum(o)).ok);assert.equal(G.serialize(),before);const p=JSON.parse(before),[a,b]=p.S.order;p.S.chars[a].master=b;p.S.chars[b].master=a;assert(!G.loadText(checksum(p)).ok);assert.equal(G.serialize(),before)});
test('automatic matching can be disabled and must preserve existing relations',()=>{const {s,t,c}=fresh();N.mentorshipDay(true);assert.equal(c.master,null);assert(N.proposeMentor(t.id,c.id).ok);s.patch.management.enabled=true;s.patch.management.autoMentors=true;N.mentorshipDay(true);assert.equal(c.master,t.id);valid()});
test('save/load and time chunks reproduce all mentorship and slot events',()=>{fresh(414);G.S.patch.management.enabled=true;G.S.patch.management.autoMentors=true;walk(25);const snap=G.serialize();walk(35);const expected=G.serialize();assert(G.loadText(snap).ok);walk(35);assert.equal(G.serialize(),expected);for(const c of G.alive()){const slots={};for(const e of c.mx.life.history){const key=e.day+'|'+e.slot;slots[key]=(slots[key]||0)+1}assert(Object.values(slots).every(n=>n<=1),c.name)}valid()});
console.log('APPRENTICESHIP',pass,'groups passed');
