const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),cp=require('node:child_process'),G=require('./harness'),X=G.CIVIL,W=G.WORLD,N=G.N,P=G.PATCH;
let passed=0;const covered=new Set();
function fresh(seed=7){G.newGame(seed);N._claims={};N._dayKeys=[];for(const k of Object.keys(G.S.res))G.S.res[k]=10000;for(const f of G.S.factions){f.wealth=10000;f.stock=10000;Object.assign(X.group(f.id).materials,{herb:100,ore:100,wood:100,stone:100});}return W.people();}
function pair(foreign=false){const f=G.S.factions[0];return foreign?f.roster.slice(1,3).map(r=>W.person(r.mx.id)):G.home().slice(1,3).map(c=>W.person(c.id));}
function valid(){const r=G.validate(G.serialize());assert(r.ok,r.msg)}
function execute(a,id,data={}){N._claims={};const p=X.make(a,id,data);assert(X.validate(a,p),id+' legal');const text=X.execute(a,p);assert(text,id+' produced a result');covered.add(id);return text}
function test(name,fn){fresh();fn();passed++;console.log('PASS',name)}
test('all original vocabulary has concrete contextual, native or outcome routes',()=>{const old=JSON.parse(fs.readFileSync(path.join(__dirname,'../data/action-keywords-v200.json'))).records;for(const d of old)assert(G.ACTIONS[d.id]?.supported,d.id);for(const d of Object.values(G.ACTIONS)){assert(d.name&&!/ · [A-Z_]+$/.test(d.name),d.id);if(d.handler==='civil'){assert.equal(typeof X.actions[d.id]?.run,'function');assert.equal(typeof X.actions[d.id]?.check,'function');}}assert.equal(Object.keys(G.ACTIONS).length,236);valid()});
test('unknown, dead, unaffordable, absent and unauthorized actions are rejected',()=>{const [a,b]=pair();assert(!X.validate(a,X.make(a,'NO_SUCH_ACTION')));assert(!W.validateAction(a,{key:'complete_goal',id:'COMPLETE_GOAL'}));assert(!W.validateAction(a,{key:'unregistered',id:'REST'}));G.S.res.herb=0;assert(!X.execute(a,X.make(a,'TREAT_WOUND')));assert(!X.execute(a,X.make(a,'CHANGE_POLICY')));b.c.state='exp';assert(!X.validate(a,X.make(a,'MAKE_FRIEND',{person:b.id})));const f=pair(true)[0];W.relate(a,f.id,{trust:50});assert(!X.validate(X.leader('player'),X.make(X.leader('player'),'PROMOTE_MEMBER',{person:f.id})));});
test('loans conserve both wallets, mark default once and can be repaid after default',()=>{const [a,b]=pair();a.b.wallet=0;b.b.wallet=30;W.relate(b,a.id,{trust:60});execute(a,'BORROW_MONEY',{person:b.id});assert.equal(a.b.wallet+b.b.wallet,30);assert.equal(X.life(a).debts[0].amount,10);a.b.wallet=0;G.S.day=61;X.daily();assert.equal(X.life(a).debts[0].status,'overdue');a.b.wallet=10;X.life(a).cooldowns={};execute(a,'REPAY_LOAN',{person:b.id});assert.equal(a.b.wallet,0);assert.equal(b.b.wallet,30);assert.equal(X.life(b).debts[0].status,'paid');valid()});
test('foreign actors use paid medicine and real item ownership and power',()=>{const [a]=pair(true),d=Object.values(P.items).find(d=>d.type==='pill'&&d.effect==='heal'&&X.itemCompatible(a,d));assert(d);X.addStock(a.group,d.id);assert(X.giveItem(a,d.id));a.c.mx.health=50;execute(a,'TAKE_MEDICINE');assert(a.c.mx.health>50);assert(!X.gear(a).some(i=>i.def===d.id));const weapon=Object.values(P.items).find(d=>d.type==='weapon'&&X.itemCompatible(a,d));X.addStock(a.group,weapon.id);const before=X.power(a);assert(X.giveItem(a,weapon.id));assert(X.power(a)>before);valid()});
test('foreign crafting spends materials immediately and delivers only after labor',()=>{const [a]=pair(true);X.group(a.group).facilities.forge=1;X.group(a.group).facilities.alchemy=1;const d=X.recipe(a);assert(d);const before=X.balance(a.group,'silver'),qty=X.stockCount(a.group,d.id);execute(a,'CRAFT',{recipe:d.id});assert(X.balance(a.group,'silver')<=before);assert.equal(X.stockCount(a.group,d.id),qty);for(let i=0;i<2000&&X.life(a).craft;i++){a.c.mx.fatigue=0;X.educationDay(a)}assert(!X.life(a).craft);assert.equal(X.stockCount(a.group,d.id),qty+1);valid()});
test('foreign study spends time and unlocks actual learned arts and mastery',()=>{const [a]=pair(true);a.c.r=4;a.c.mx.foundation=100;const id=X.learnable(a);assert(id);execute(a,'STUDY_TECHNIQUE',{art:id});assert(!X.arts(a).includes(id));for(let i=0;i<2000&&X.life(a).study;i++){a.c.mx.fatigue=0;X.educationDay(a)}assert(X.arts(a).includes(id));assert.equal(X.mastery(a,id),25);execute(a,'TRAIN_MARTIAL_ART',{art:id});assert(X.mastery(a,id)>25);valid()});
test('caravan escrow conserves total silver and stock before and after delivery',()=>{const from='player',to=G.S.factions[0].id,e=W.state().economy;G.S.factions.find(f=>f.id==='f6').dead=true;e.routeSafety=1;const total=X.balance(from,'silver')+X.balance(to,'silver'),food=X.balance(from,'food')+X.balance(to,'food');const c=X.caravan(from,to,'food',5,8);assert(c);assert.equal(X.balance(from,'silver')+X.balance(to,'silver')+c.price,total);assert.equal(X.balance(from,'food')+X.balance(to,'food')+c.qty,food);for(let i=0;i<5;i++)X.caravansDay();assert.equal(c.status,'delivered');assert.equal(X.balance(from,'silver')+X.balance(to,'silver'),total);assert.equal(X.balance(from,'food')+X.balance(to,'food'),food);valid()});
test('caravan loss transfers actual cargo to bandits and returns escrow',()=>{W.state().economy.routeSafety=.25;const c=X.caravan('player',G.S.factions[0].id,'food',5,8),bandit=G.S.factions.find(f=>f.id==='f6'),before=bandit.stock,to=c.to,coins=X.balance(to,'silver');let seed=1;while(N.hash(c.id+'|'+seed)%1000>=.75*.65*1000)seed++;G.S.seed=seed;for(let i=0;i<5;i++)X.caravansDay();assert.equal(c.status,'lost');assert.equal(bandit.stock,before+5);assert.equal(X.balance(to,'silver'),coins+8);valid()});
test('physical journeys consume supplies, return and restore prior duty',()=>{const [a]=pair();a.c.jobFix=0;G.S.patch.management.autoMissions=true;const before=G.S.res.food,job=a.c.job;execute(a,'VISIT_CITY',{location:'silkroad'});assert(G.S.res.food<before);assert.equal(a.c.state,'civilTravel');valid();for(let i=0;i<30&&X.life(a).travel;i++)X.journeysDay();assert(!X.life(a).travel);assert.equal(a.c.state,'home');assert.equal(a.c.job,job);valid()});
test('travellers can return or flee; visitors can meet known foreign people',()=>{const [a]=pair(true),to=G.S.factions[1].id;X.startTravel(a,to,'VISIT_SECT');X.life(a).travel.remaining=1;X.journeysDay();const t=X.leader(to);assert(X.knows(a,t.id));assert(X.near(a,t));execute(a,'MAKE_FRIEND',{person:t.id});assert(W.rel(t,a.id).affection>0);execute(a,'RETURN_HOME');assert.equal(X.life(a).travel.phase,'back');a.c.mx.health=50;execute(a,'FLEE');valid()});
test('captives stop normal activities and can escape using actual guard strength',()=>{const [a,b]=pair(true);X.life(a).captive={captor:b.id,group:b.group,since:0,verdict:false};assert(!W.available(a));assert(!X.validate(a,X.make(a,'SOCIALIZE',{person:b.id})));X.group(b.group).security=0;execute(a,'FLEE');assert(!X.life(a).captive);assert(W.available(a));valid()});
test('complaints pay compensation and reduce actual grievance',()=>{const [a]=pair();X.life(a).grievance=60;a.b.wallet=0;execute(a,'FILE_PETITION');const leader=X.leader('player'),silver=G.S.res.silver;execute(leader,'RESOLVE_GRIEVANCE',{person:a.id});assert.equal(a.b.wallet,2);assert.equal(G.S.res.silver,silver-2);assert.equal(X.life(a).petition.status,'resolved');assert(X.life(a).grievance<60);valid()});
function crisis(foreign=false){const group=foreign?G.S.factions[0].id:'player',people=X.members(group),leader=X.leader(group),a=people.find(p=>p.id!==leader.id);G.S.day=200;if(a.f)a.c.mx.role='ผู้อาวุโส';else a.c.rank=3;for(const p of people){p.b.cohort=p.id===leader.id?leader.id:a.id;X.life(p).grievance=80;X.sat(p,-60)}X.life(a).influence=20;const g=X.group(group);g.legitimacy=20;g.unrest=80;return {group,a,leader,g,people}}
for(const foreign of [false,true])test((foreign?'foreign':'player')+' elder challenge follows supporters and council vote',()=>{const {group,a,leader,g}=crisis(foreign);execute(a,'CHALLENGE_AUTHORITY');assert.equal(X.leader(group).id,leader.id);assert(g.case);X.resolveCase(group,'vote');G.S.day=g.case.due;execute(a,'VOTE_NO_CONFIDENCE');assert.equal(X.leader(group).id,a.id);assert(!g.case);valid()});
test('a funded audit resolves a crisis without removing the leader',()=>{const {a,leader,g}=crisis();execute(a,'CHALLENGE_AUTHORITY');const before=G.S.res.silver;assert(X.resolveCase('player','audit'));assert.equal(G.S.res.silver,before-10);assert.equal(X.leader('player').id,leader.id);assert(!g.case);assert(g.legitimacy>20);valid()});
test('coup requires refusal, severe legitimacy crisis and supporters; injuries persist',()=>{const {a,leader,g,people}=crisis();a.c.at.cou=95;a.c.realm=4;leader.c.realm=0;execute(a,'CHALLENGE_AUTHORITY');assert(!X.validate(a,X.make(a,'COUP')));X.resolveCase('player','refuse');G.S.day=g.case.due;execute(a,'COUP');assert(people.some(p=>p.c.hp<100));assert(!g.case);valid()});
test('adult mutual marriage and family care respect real relationships',()=>{const [a,b]=pair(true);a.c.mx.born=b.c.mx.born=-25*360;W.relate(a,b.id,{affection:80,trust:80});W.relate(b,a.id,{affection:80,trust:80});execute(a,'PROPOSE_MARRIAGE',{person:b.id});execute(b,'MARRY',{person:a.id});assert.equal(X.life(a).partner,b.id);assert.equal(X.life(b).partner,a.id);execute(a,'VISIT_FAMILY',{person:b.id});b.c.mx.health=60;execute(a,'CARE_FOR_FAMILY',{person:b.id});assert(b.c.mx.health>60);valid()});
test('nonlethal duel cannot randomly kill either participant',()=>{const [a,b]=pair();a.c.realm=4;b.c.realm=0;const ids=G.S.order.slice();for(let i=0;i<8;i++){a.c.hp=b.c.hp=100;a.c.fat=b.c.fat=0;X.duel(a,b,'DUEL')}assert.deepEqual(G.S.order,ids);assert(X.life(b).wounds>0);valid()});
test('bilateral wars and peace update native diplomacy and disrupt routes',()=>{const a=X.leader(G.S.factions[0].id),to=G.S.factions[1].id,r=X.diplomacy(a.group,to);W.learn(a,W.emit('VISIT_SECT',null,X.leader(to).id,'ข้อมูลจากทูต',{group:to,witnesses:[]}), 'merchant');r.relation=-70;r.hostility=80;X.group(a.group).intel[to]={day:0,power:5,wealth:100,confidence:.7};execute(a,'DECLARE_WAR',{group:to});assert(Object.hasOwn(a.f.war,to));assert(Object.hasOwn(G.S.factions[1].war,a.group));X.group(to).unrest=50;X.group(a.group).unrest=50;execute(a,'OFFER_TRIBUTE',{group:to});assert(!X.war(a.group,to));assert(!Object.hasOwn(a.f.war,to));valid()});
test('observational capture stores pre-action alternatives and real horizons',()=>{const [a]=pair(true),q=X.state().training;q.enabled=true;q.decisions=19;a.c.mx.health=60;execute(a,'REST');assert.equal(q.pending.length,1);const x=q.pending[0];assert.equal(x.features.health,60);assert(x.after.health>x.before.health);assert(x.alternatives.length);for(const h of [30,90,180]){G.S.day=h;X.outcomesDay()}assert.equal(q.samples.length,1);assert.deepEqual(q.samples[0].outcomes.map(o=>o.horizon),[30,90,180]);const data=JSON.parse(X.exportTraining());assert.equal(data.kind,'observational_decision_outcomes');valid()});
test('schema-8 malformed fields and inventories reject atomically',()=>{const save=G.serialize();function pack(s){const body=JSON.stringify(s);let h=5381;for(let i=0;i<body.length;i++)h=((h<<5)+h+body.charCodeAt(i))|0;return JSON.stringify({game:'sect',S:s,sum:h})}for(const mutate of [s=>s.patch.civil.groups.player.legitimacy=NaN,s=>s.chars[s.order[0]].mx.brain.civil.partner='missing',s=>s.patch.civil.training.pending=Array(129).fill({}),s=>s.patch.civil.groups.player.stockItems.bad=1,s=>s.chars[s.order[0]].mx.brain.civil.qi=-1,s=>delete s.patch.civil]){const s=JSON.parse(save).S;mutate(s);assert(!G.loadText(pack(s)).ok);assert.equal(G.serialize(),save)}});
test('official actual 2.0 save migrates without changing RNG, assets or identities',()=>{const old=fs.readFileSync(path.join(__dirname,'fixtures/real-v200.json'),'utf8'),s=JSON.parse(old).S;assert(G.loadText(old).ok);assert.equal(G.S.schema,8);assert.equal(G.S.rng,s.rng);assert.equal(G.S.day,s.day);assert.deepEqual(G.S.res,s.res);assert.deepEqual(G.S.patch.items,s.patch.items);assert.deepEqual(G.S.order,s.order);valid();});
test('dissolved sects cannot receive new transfers and their parcels are refunded',()=>{const f=G.S.factions[0],sum=G.S.res.silver+f.wealth,food=G.S.res.food+f.stock,c=X.caravan('player',f.id,'food',5,8);f.dead=true;const before=G.S.res.food;assert(!X.transfer('player',f.id,'food',2));assert.equal(G.S.res.food,before);X.caravansDay();assert.equal(c.status,'cancelled');assert.equal(G.S.res.silver+f.wealth,sum);assert.equal(G.S.res.food+f.stock,food);W.cleanup();valid()});
test('a coup counts the challenger power once rather than twice',()=>{const {a,leader,g}=crisis();a.c.at.cou=95;execute(a,'CHALLENGE_AUTHORITY');X.resolveCase('player','refuse');G.S.day=g.case.due;const power=X.power;try{X.power=t=>t.id===a.id?100:t.id===leader.id?190:1;execute(a,'COUP');assert.equal(X.leader('player').id,leader.id);}finally{X.power=power}valid()});
test('new canonical IDs and structured plans are validated',()=>{assert.equal(N.actionId('civil_file_petition'),'FILE_PETITION');const [a]=pair();a.c.mx.life.plan={key:'civil_make_friend',id:'MAKE_FRIEND',score:20,why:'test',since:0,until:0,target:null,data:{person:pair()[1].id}};valid();const text=G.serialize();a.c.mx.life.plan.data.bad=()=>0;assert.throws(()=>X.validateSave(G.S),/ข้อมูลแผน/);delete a.c.mx.life.plan.data.bad;assert(G.loadText(text).ok);valid()});
test('historical sect snapshots do not duplicate living AI brains',()=>{G.stepDay();for(const f of G.S.factions){for(const r of f.mx.previous)assert(!r.brain);for(const r of f.roster)assert(r.mx.brain?.civil)}valid()});
test('save-resume remains deterministic with new actions and training enabled',()=>{X.state().training.enabled=true;const walk=n=>{for(let i=0;i<n;i++){G.stepDay();for(const p of G.S.pending.slice())G.decide(p.id,p.def)}};walk(12);const save=G.serialize();walk(12);const expected=G.serialize();assert(G.loadText(save).ok);walk(12);assert.equal(G.serialize(),expected);valid()});
fs.writeFileSync(path.join(__dirname,'results-v210-contracts.json'),JSON.stringify({passed,covered:[...covered].sort(),registry:Object.keys(G.ACTIONS).length,contextual:Object.keys(X.actions).length,note:'Coverage lists actions exercised by explicit assertions; this is not proof every action is selected in natural play.'},null,2));
console.log('CIVIL 2.1 PASS',passed,'scenario groups;',covered.size,'actions with direct assertions');
