const assert=require('node:assert/strict'),G=require('./harness');const N=G.N,P=G.PATCH;let passed=0;const test=(name,fn)=>{try{fn();passed++;console.log('PASS',name)}catch(e){console.error('FAIL',name,e);process.exitCode=1}},fresh=(seed=2026)=>{G.newGame(seed);G.S.patch.management.autoStudy=false;return G.S},walk=n=>{for(let i=0;i<n&&!G.S.over;i++){G.stepDay();for(const p of G.S.pending.slice())G.decide(p.id,p.def)}},valid=()=>{const r=G.validate(G.serialize());assert(r.ok,r.msg)};

test('new games are schema 6 with deep life flags',()=>{fresh();assert.equal(G.S.schema,G.SCHEMA);assert.equal(G.VERSION,'2.1.0');assert.equal(G.S.patch.management.deepLife,true);assert.equal(G.S.patch.management.leaderUse,true);valid()});

test('people use several time slots and do not repeat the same act every day',()=>{fresh(11);walk(21);for(const c of G.alive()){assert(c.mx.life.history.length>=6,c.name);const days={};for(const x of c.mx.life.history)(days[x.day]??=[]).push(x.key);const filled=Object.values(days).filter(xs=>xs.length>=3);assert(filled.length>=3,c.name+' slots');const seq=c.mx.life.history.slice().reverse().map(x=>x.key);let streak=1,max=1;for(let i=1;i<seq.length;i++){streak=seq[i]===seq[i-1]?streak+1:1;max=Math.max(max,streak)}assert(max<=8,c.name+' streak '+max);assert(new Set(seq).size>=4,c.name+' variety')}valid()});

test('duty and personality both change the daily agenda',()=>{fresh();const c=G.home()[4];c.job='farm';c.jobFix=1;c.at.soc=10;c.at.amb=20;c.traits=[];N._planningSlot='morning';const farm=N.planAgenda(c,G.home());c.job='cultivate';c.at.soc=95;c.at.amb=90;c.traits=['sm_ambitious','sm_social'];N._planningSlot='night';const night=N.planAgenda(c,G.home());assert(farm.some(x=>['supply','garden','help_other','maintain','cook'].includes(x.key))||farm.filter(x=>x.slot==='morning'||x.slot==='dawn').length);assert(night.some(x=>['secret','social','practice','write','stargaze','court'].includes(x.key)));assert(farm.map(x=>x.key).join()!==night.map(x=>x.key).join())});

test('leader style changes who receives leftover gear',()=>{fresh();const lead=G.S.chars[G.S.sect.leader],m=G.S.patch.management;m.autoEquip=true;m.itemReserve=0;m.budget=1000;m.autoPills=false;m.leaderUse=true;m.enabled=true;const fighter=G.home().find(c=>c!==lead);fighter.job='guard';fighter.at.cou=99;lead.at.cou=99;lead.at.int=20;lead.traits=['sm_ambitious'];const i=N.addItem('iron_sword',1);assert(i);N.processItems();assert(G.home().some(c=>N.owned(c,'weapon')),'martial-leaning leader equips a free sword');valid()});

test('scholar leader spends a found scroll into a real copy job',()=>{fresh();const lead=G.S.chars[G.S.sect.leader],m=G.S.patch.management,a=Object.values(P.arts).find(a=>!G.S.patch.knownArts.includes(a.id)&&a.tier<=2);m.autoSell=false;m.leaderUse=true;m.enabled=true;lead.at.int=99;lead.traits=['sm_mentorGift'];G.S.fac.library=1;G.S.res.silver=500;G.S.res.wood=80;m.autoStudy=true;m.itemReserve=0;N.addItem(N.scrollId(a.id));G.S.patch.worldLife.lastUtilize=-1;G.S.patch.worldLife.utilizeRev=-1;N.leaderUtilize();assert(G.S.patch.library.copies.length>=1||G.S.patch.knownArts.includes(a.id));valid()});

test('cautious leader does not dump the reserve on vanity projects',()=>{fresh();const lead=G.S.chars[G.S.sect.leader],m=G.S.patch.management;lead.traits=['sm_cautious','sm_timid'];lead.at.cau=99;lead.at.amb=10;m.autoBuild=true;m.reserve=200;G.S.res.silver=210;G.S.res.wood=20;G.S.patch.worldLife.lastCouncil=-3;N.councilDay();assert(G.S.res.silver>=m.reserve||G.S.buildQ.length===0);valid()});

test('spawned medicine is used on an actually hurt member',()=>{fresh();const m=G.S.patch.management,hurt=G.home()[3];m.autoPills=true;m.itemReserve=0;m.budget=1000;m.leaderUse=true;m.enabled=true;hurt.hp=40;hurt.inj=[{n:'ทดลอง',sev:1,days:4}];N.addItem('root_pill',2);G.S.patch.worldLife.lastUtilize=-1;G.S.patch.worldLife.utilizeRev=-1;N.processItems();assert(hurt.hp>40);valid()});

test('schema 4 save migrates to 6 without extra stock',()=>{fresh(9);const o=JSON.parse(G.serialize());o.S.schema=4;o.ver='1.3.0';delete o.S.patch.management.deepLife;delete o.S.patch.management.leaderUse;delete o.S.patch.worldLife.pulse;delete o.S.patch.worldLife.leaderUses;delete o.S.patch.worldLife.considerations;delete o.S.patch.worldLife.worldEvents;delete o.S.patch.worldLife.style;delete o.S.patch.worldLife.utilizeRev;delete o.S.patch.worldLife.lastPulse;delete o.S.patch.worldLife.lastUtilize;for(const c of Object.values(o.S.chars)){delete c.mx.life.agenda;delete c.mx.life.mood;delete c.mx.life.habits;delete c.mx.life.projects;delete c.mx.life.variety;delete c.mx.life.slotCounts;for(const e of c.mx.life.history||[])delete e.slot}const body=JSON.stringify(o.S);let h=5381;for(let i=0;i<body.length;i++)h=((h<<5)+h+body.charCodeAt(i))|0;o.sum=h;o.schema=4;const silver=o.S.res.silver,arts=o.S.patch.knownArts.slice();const r=G.loadText(JSON.stringify(o));assert(r.ok,r.msg);assert.equal(G.S.schema,G.SCHEMA);assert.equal(G.S.res.silver,silver);assert.deepEqual(G.S.patch.knownArts,arts);assert.equal(G.S.patch.management.deepLife,true);walk(5);valid()});

test('foreign daily lives stay inside finite wealth and history',()=>{fresh(5);walk(40);assert(G.S.patch.worldLife.foreignActions>20);for(const f of G.S.factions){assert(f.wealth>=0&&f.stock>=0);assert(f.roster.every(r=>!r.mx.sideHistory||r.mx.sideHistory.length<=24))}valid()});

test('save resume stays deterministic after deep days',()=>{fresh(414);walk(40);const snap=G.serialize();walk(25);const expected=G.serialize();assert(G.loadText(snap).ok);walk(25);assert.equal(G.serialize(),expected)});

console.log('DEEP',passed,'groups passed');
