const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path'),G=require('./harness'),els={},listeners={};let renders=0,actions=0;
const el=id=>els[id]||(els[id]={id,innerHTML:'',className:'',value:'',checked:false,scrollTop:0,firstChild:null,textContent:'',files:[],querySelector(){return null}});global.document={getElementById:el,addEventListener(k,fn){(listeners[k]??=[]).push(fn)},querySelector(){return null},querySelectorAll(){return []},body:{appendChild(){}}};global.history={pushState(){}};global.addEventListener=()=>{};global.confirm=()=>true;global.navigator={};['ui','ui2','patch-ui','parity-ui','living-ui','living-deep-ui','apprenticeship-ui','world-ui'].forEach(f=>vm.runInThisContext(fs.readFileSync(path.join(__dirname,'../js',f+'.js'),'utf8'),{filename:f}));const U=G.UI,A=U.A,N=G.N,P=G.PATCH;U.boot();G.newGame(2026);G.S.patch.cheat=true;G.S.patch.management.autoStudy=false;
const check=h=>{assert(h&&h.length>0);assert(!/undefined|NaN|\[object/.test(h));for(const m of h.matchAll(/data-a="([^"]+)"/g))assert.equal(typeof A[m[1]],'function',m[1]);renders++},hydrate=h=>{for(const m of h.matchAll(/<input\b([^>]+)>/g)){const id=m[1].match(/id="([^"]+)"/)?.[1];if(!id)continue;el(id).value=m[1].match(/value="([^"]*)"/)?.[1]||'';el(id).checked=/\bchecked/.test(m[1])}};
let seen=new Set;for(const type of Object.keys(P.categories)){A['p-edit-category']({type});const defs=N.editDefinitions();for(let i=0;i<Math.ceil(defs.length/20);i++){U.editFilter.page=i;const h=N.views.editor();check(h);for(const m of h.matchAll(/data-a="p-spawn" data-id="([^"]+)"/g))seen.add(m[1])}}assert.equal(seen.size,800);
// Reproduce the input focus bug through the actual delegated click listener.
let renderCalls=0;const render=U.render;U.render=()=>{renderCalls++;return render()};const input={id:'edit-count',tagName:'INPUT',type:'text',value:'',dataset:{a:'p-edit-option',key:'quantity'}};for(const fn of listeners.click)fn({target:{closest:()=>input}});assert.equal(renderCalls,0,'touching a numeric field must not rerender');for(const v of ['','1','10','100']){input.value=v;for(const fn of listeners.input)fn({target:input})}assert.equal(U.editFilter.quantity,100);assert.equal(renderCalls,0);A.lwquantity({n:'1000'});assert.equal(el('edit-count').value,'1000');G.S.patch.management.enabled=false;A['p-spawn']({id:'foundation_pill'});assert(N.itemCount('foundation_pill')>=1000);actions++;
const c=G.home()[4];el('edit-person').value=c.id;A.lweditopen();let h=U.M.lwcharacter();check(h);hydrate(h);const snapshot=G.serialize();A.lwtrait({id:'sm_fair'},{checked:true});A.lwtrait({id:'sm_organizer'},{checked:true});assert.equal(G.serialize(),snapshot,'selecting traits must only change draft');assert(U.characterDraft.traits.includes('sm_fair'));assert(U.characterDraft.traits.includes('sm_organizer'));el('ce-name').value='ศิษย์ทดสอบ';el('ce-age').value='33';A.lweditpath({},{value:'body'});h=U.M.lwcharacter();hydrate(h);A.lweditrealm({},{value:'3'});el('ce-at-admin').value='99';A.lweditsave();assert.equal(c.name,'ศิษย์ทดสอบ');assert.equal(c.path,'body');assert.equal(c.realm,3);assert.equal(c.at.admin,99);assert(c.traits.includes('sm_fair'));assert.equal(U.modalStack.length,0);actions++;
el('edit-person').value=c.id;A.lweditopen();h=U.M.lwcharacter();hydrate(h);const beforeCancel=G.serialize();el('ce-name').value='ต้องไม่บันทึก';A.lwclose();assert.equal(G.serialize(),beforeCancel);actions++;
const a=Object.values(P.arts).find(a=>!G.S.patch.knownArts.includes(a.id)&&a.tier<=2),i=N.addItem(N.scrollId(a.id));check(U.M.mxitem(i.id));A.lwcopyopen({id:i.id});check(U.M.lwpermission());A.lwrank({rank:'0'},{checked:false});A.lwpermissionperson({id:c.id},{checked:true});A.lwpermissionsave();assert(G.S.patch.library.copies.length===1);assert(!G.S.patch.knownArts.includes(a.id));for(let k=0;k<100&&G.S.patch.library.copies.length;k++)N.workCopy(c,1);A.lwruleopen({id:a.id});check(U.M.lwpermission());A.lwrank({rank:'3'},{checked:false});A.lwpermissionsave();assert(!G.S.patch.library.rules[a.id].ranks.includes(3));assert(G.S.patch.library.rules[a.id].people.includes(c.id));actions++;
const unrelated=Object.values(P.arts).find(a=>!G.S.patch.knownArts.includes(a.id));assert(!N.views.arts().includes(unrelated.name));check(U.M.mxart(unrelated.id));check(U.M.mxart(a.id));U.open('mxart',a.id);assert(el('modal').innerHTML.includes('✕ ปิด'));assert(el('modal').innerHTML.includes('sheet-head'));A.lwclose();assert(el('modal').className==='hide');actions++;
for(let d=0;d<180;d++){G.stepDay();for(const p of G.S.pending.slice())G.decide(p.id,p.def);if(d%30===0){for(const fn of Object.values(N.views))check(fn());for(const person of G.alive())check(U.M.char(person.id));}}
const save=G.serialize(),rng=G.S.rng;for(let k=0;k<4;k++){check(N.views.lives());check(N.views.people());check(N.views.steward());check(N.views.arts());check(N.views.council())}assert.equal(G.serialize(),save);assert.equal(G.S.rng,rng);assert(G.loadText(save).ok);console.log('LIVING UI PASS',renders,'renders;',actions,'interaction flows; focus-safe quantity, atomic drafts, permissions, close, all 800 definitions');clearTimeout(U._tt);
