const assert=require('node:assert/strict'),G=require('./harness'),W=G.WORLD,N=G.N,P=G.PATCH;let passed=0;
function reset(seed=7){G.newGame(seed);for(const k in G.S.pauseCfg)G.S.pauseCfg[k]=0;return G.S}
function test(name,fn){reset();fn();passed++;console.log('PASS',name)}
function checksum(s){const b=JSON.stringify(s);let h=2166136261;for(let i=0;i<b.length;i++){h^=b.charCodeAt(i);h=Math.imul(h,16777619)}return (h>>>0).toString(16)}
function repack(s){return JSON.stringify({game:'sect',ver:G.VERSION,sum:checksum(s),S:s})}
function valid(){const r=G.validate(G.serialize());assert(r.ok,r.msg)}
test('schema and canonical action registry',()=>{assert.equal(G.VERSION,'2.1.0');assert.equal(G.S.schema,G.SCHEMA);assert(Object.keys(G.ACTIONS).length>=190);for(const [id,a]of Object.entries(G.ACTIONS)){assert.equal(id,a.id);assert(a.category&&a.description&&a.actors&&a.requirements&&a.targets&&a.tags)}valid()});
test('needs and goals derive from actual injury poverty and ambition',()=>{const a=W.person(G.home()[1].id);a.c.hp=40;a.c.fat=80;a.c.at.amb=90;W.review(a);assert(a.b.goals.some(g=>g.kind==='recover'));assert(a.b.goals.some(g=>g.kind==='wealth'));assert(a.b.goals.some(g=>g.kind==='status'));assert(a.b.needs.healing>90)});
test('plan advances only on executed steps and goal success requires real change',()=>{const a=W.person(G.home()[1].id);W.needs(a);W.addGoal(a,'status');const g=a.b.goals.find(g=>g.kind==='status');W.record(a,'HELP_PERSON','ช่วยจริง');assert.equal(g.cursor,1);a.b.lastReview=-99;W.review(a);assert.equal(g.cursor,1);assert(a.b.goals.includes(g));a.c.rank=g.base+1;a.b.lastReview=-99;W.review(a);assert(!a.b.goals.includes(g));assert(a.b.goalHistory.some(x=>x.kind==='status'&&x.result==='complete'))});
test('personal currency is transferred from actual paid treasury',()=>{const a=W.person(G.home()[1].id);G.S.patch.management.reserve=0;G.S.res.silver=1000;const before=G.S.res.silver+a.b.wallet;assert(W.validateAction(a,{key:'earn_money',id:'EARN_MONEY'}));W.execute(a,{key:'earn_money'});assert.equal(G.S.res.silver+a.b.wallet,before);assert.equal(a.b.wallet,2);G.S.res.silver=0;assert(!W.validateAction(a,{key:'earn_money',id:'EARN_MONEY'}))});
test('paid stipends credit only the actual allowed stipend portion',()=>{const all=W.people().filter(a=>!a.f),before=all.reduce((n,a)=>n+a.b.wallet,0),cash=G.S.res.silver;G.add('silver',-1,'ค่าบำรุงและเบี้ยเลี้ยง');const delta=all.reduce((n,a)=>n+a.b.wallet,0)-before;assert(delta<=1+1e-9);assert(delta>=0);assert.equal(G.S.res.silver,cash-1)});
test('reward money reaches savings once without creating extra money',()=>{const c=G.home()[1],a=W.person(c.id),total=G.S.res.silver+a.b.wallet;assert(G.reward(c,'silver').ok);assert.equal(G.S.res.silver+a.b.wallet,total);assert.equal(a.b.wallet,30)});
test('medicine purchase consumes real item and respects reserve and flags',()=>{const a=W.person(G.home()[1].id);a.c.hp=30;a.b.wallet=10000;const i=N.addItem('root_pill',4);G.S.patch.management.itemReserve=0;const heal=Object.values(P.items).find(d=>d.type==='pill'&&d.effect==='heal'&&d.grade<=2&&d.minRealm<=a.c.realm&&(!d.paths.length||d.paths.includes(a.c.path)));assert(heal);N.addItem(heal.id,3);const n=N.itemCount(heal.id),total=a.b.wallet+G.S.res.silver;const got=W.execute(a,{key:'buy_personal'});assert(got);assert(N.itemCount(heal.id)<n);assert(Math.abs(a.b.wallet+G.S.res.silver-total)<1e-8);G.S.patch.management.autoPills=false;assert(!W.validateAction(a,{key:'buy_personal',id:'BUY_ITEM'}));i.locked=true;valid()});
test('favor repayment conserves money and changes debt and trust',()=>{const [c,t]=G.home().slice(1,3),a=W.person(c.id),b=W.person(t.id);a.b.wallet=5;W.relate(a,b.id,{debt:4,gratitude:30});const total=a.b.wallet+b.b.wallet;assert(W.validateAction(a,{key:'repay_favor',id:'REPAY_FAVOR',target:b.id}));W.execute(a,{key:'repay_favor',target:b.id});assert.equal(a.b.wallet+b.b.wallet,total);assert.equal(W.rel(a,b.id).debt,2);assert(W.rel(b,a.id).trust>0)});
test('unwitnessed private events are unknown and information spreads with delay',()=>{const [c,t]=G.home().slice(1,3),a=W.person(c.id),b=W.person(t.id);const e=W.emit('GIVE_GIFT',c.id,c.id,'ได้รับของส่วนตัว',{witnesses:[c.id],importance:85});assert(a.b.knowledge.some(k=>k.event===e.id));assert(!b.b.knowledge.some(k=>k.event===e.id));assert(!W.people().filter(x=>x.f).some(x=>x.b.knowledge.some(k=>k.event===e.id)));for(let d=0;d<12;d++){G.S.day++;W.spread()}assert(W.people().filter(x=>!x.f&&x.id!==a.id).some(x=>x.b.knowledge.some(k=>k.event===e.id)))});
test('false or exaggerated claims are corrected from a real source',()=>{const a=W.person(G.home()[1].id),e=W.emit('LEARN_RUMOR',null,null,'พื้นที่มีสมุนไพร 12 หน่วย',{location:'herbwood',witnesses:[]});W.learn(a,e,'merchant',.4,'พื้นที่มีสมุนไพร 999 หน่วย');assert(!a.b.knowledge[0].verified);assert(W.execute(a,{key:'verify_news'}));assert.equal(a.b.knowledge.find(k=>k.event===e.id).claim,e.text);assert(a.b.knowledge.find(k=>k.event===e.id).verified)});
test('legendary gift creates witnessed jealousy and gratitude',()=>{const [leader,c,t]=G.home();t.rank=c.rank;t.at.amb=95;const d=Object.values(P.items).find(d=>d.type==='weapon'&&d.grade>=3);assert(d);c.realm=Math.max(c.realm,d.minRealm);if(d.paths.length)c.path=d.paths[0];const i=N.addItem(d.id);assert.equal(N.equip(i.id,c.id),'');assert(W.rel(W.person(c.id),leader.id).gratitude>0);assert(W.rel(W.person(t.id),c.id).jealousy>0);assert(W.person(t.id).b.memories.some(m=>m.type==='BECOME_JEALOUS'))});
test('rivalry produces actual duel result memories and recovery need',()=>{const [c,t]=G.home().slice(1,3),a=W.person(c.id),b=W.person(t.id);t.realm=c.realm;W.relate(a,b.id,{rivalry:40,hatred:20});assert(W.validateAction(a,{key:'challenge_rival',id:'CHALLENGE',target:b.id}));W.execute(a,{key:'challenge_rival',target:b.id});assert(a.b.memories.concat(b.b.memories).some(m=>m.type==='LOSE_DUEL'));assert(c.hp<100||t.hp<100)});
test('death returns private savings and removes live relationship references',()=>{const [c,t]=G.home().slice(1,3),a=W.person(c.id),b=W.person(t.id);a.b.wallet=12;W.relate(b,c.id,{trust:50});const before=G.S.res.silver;G.die(c,'ทดสอบ');assert.equal(G.S.res.silver,before+12);assert(!b.b.relations[c.id]);assert(b.b.memories.some(m=>m.type==='MOURN'));assert(!W.validateAction(a,{key:'earn_money',id:'EARN_MONEY'}));valid()});
test('war disrupts routes and raises actual medicine market price',()=>{W.economyDay();const price=W.state().economy.medicinePrice,safe=W.state().economy.routeSafety;G.S.factions[0].stance='war';G.S.day++;W.economyDay();assert(W.state().economy.routeSafety<safe);assert(W.state().economy.medicinePrice>price);assert(G.S.market.pillHeal>1)});
test('foreign windfall is spent on real healing and production',()=>{const f=G.S.factions[0];f.wealth=100000;f.stock=1000;f.roster[0].mx.health=50;const hp=f.roster[0].mx.health,wealth=f.wealth;W.factionDecision(f);assert(f.wealth<wealth);assert(f.roster[0].mx.health>hp);assert(f.mx.organization.history.length>=2);assert(f.mx.organization.production>0||f.mx.organization.library>0);valid()});
test('travel requires known verified location, food and explicit autonomy',()=>{const a=W.person(G.home()[1].id);a.c.jobFix=0;a.c.mx.managementLock=false;a.c.hp=100;a.c.fat=0;a.c.realm=3;G.S.res.food=10000;const e=W.emit('LEARN_RUMOR',null,null,'พบสมุนไพรที่ป่า',{location:'herbwood',witnesses:[]});W.learn(a,e,'merchant',.5);G.S.patch.management.autoMissions=true;assert(!W.validateAction(a,{key:'start_journey',id:'TRAVEL'}));W.execute(a,{key:'verify_news'});assert(W.validateAction(a,{key:'start_journey',id:'TRAVEL'}));const food=G.S.res.food;assert(W.execute(a,{key:'start_journey'}));assert(G.S.res.food<food);assert.equal(a.c.state,'worldTravel');valid();for(let d=0;d<40&&a.b.travel;d++){G.S.day++;W.journeys()}assert(!a.b.travel);assert.equal(a.c.state,'home');assert(a.b.memories.some(m=>m.type==='RETURN_HOME'));valid()});
test('quality changes affect frequency and bounded state',()=>{const cfg=W.QUALITY;assert(cfg.DEEP.memories>cfg.LOW.memories);assert(cfg.LOW.interval>cfg.DEEP.interval);for(const mode of ['LOW','NORMAL','DEEP']){reset();W.state().quality=mode;for(let d=0;d<30;d++)G.stepDay();valid();for(const a of W.people()){assert(a.b.memories.length<=cfg[mode].memories);assert(a.b.knowledge.length<=cfg[mode].knowledge)}}});
test('debug traces show real candidates scores and changes',()=>{W.state().debug=true;for(let d=0;d<3;d++)G.stepDay();assert(G.home().some(c=>c.mx.brain.trace.some(t=>t.candidates?.length&&t.reasons&&t.delta)));valid()});
test('malformed world saves reject atomically',()=>{const snapshot=G.serialize();for(const mutate of [s=>s.patch.simulation.quality='ULTRA',s=>s.chars[s.order[0]].mx.brain.wallet=-1,s=>s.chars[s.order[0]].mx.brain.knowledge=[{event:'bad'}],s=>s.patch.simulation.events=[{id:'bad'}],s=>s.chars[s.order[0]].mx.brain.relations.bad={trust:1}]){const s=JSON.parse(snapshot).S;mutate(s);assert(!G.loadText(repack(s)).ok);assert.equal(G.serialize(),snapshot)}});
test('resume preserves all decision chains and random state exactly',()=>{for(let d=0;d<15;d++)G.stepDay();const save=G.serialize();for(let d=0;d<15;d++)G.stepDay();const end=G.serialize();assert(G.loadText(save).ok);for(let d=0;d<15;d++)G.stepDay();assert.equal(G.serialize(),end);valid()});
console.log('WORLD 2.0 PASS',passed,'groups');
